=== cphzyl1611/apt-experiment-artifacts/current86-r4/FA1B2de_Current86_BSO_A2_P0_P1_Execution_Contract_R5/00_lineage/r2_baseline/05_schemas/proposal_input_bundle.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": false,
  "properties": {
    "active_authority_id": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    },
    "admissible_source_fact_set_hash": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    },
    "authority_scope_id": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    },
    "candidate_source_bundle_hashes": {
      "items": {
        "pattern": "^[0-9a-f]{64}$",
        "type": "string"
      },
      "type": "array"
    },
    "complete_candidate_relation_set_hash": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    },
    "complete_candidate_universe_hash": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    },
    "execution_manifest_id": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    },
    "historical_output_denylist_hash": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    },
    "input_status": {
      "const": "FROZEN_PREPARATION_ONLY"
    },
    "proposal_evidence_profile_hash": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    },
    "proposal_input_bundle_id": {
      "anyOf": [
        {
          "pattern": "^[0-9a-f]{64}$",
          "type": "string"
        },
        {
          "const": null
        }
      ]
    },
    "raw_identity_hash": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    },
    "raw_key": {
      "pattern": "^[0-9]+::S[0-9]{2}::A[0-9]{3}$",
      "type": "string"
    },
    "raw_source_bundle_hash": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    },
    "schema": {
      "minLength": 1,
      "type": "string"
    },
    "source_class_fact_type_registry_id": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    }
  },
  "required": [
    "schema",
    "authority_scope_id",
    "raw_key",
    "active_authority_id",
    "execution_manifest_id",
    "raw_identity_hash",
    "raw_source_bundle_hash",
    "complete_candidate_universe_hash",
    "complete_candidate_relation_set_hash",
    "candidate_source_bundle_hashes",
    "admissible_source_fact_set_hash",
    "proposal_evidence_profile_hash",
    "source_class_fact_type_registry_id",
    "historical_output_denylist_hash",
    "input_status",
    "proposal_input_bundle_id"
  ],
  "schema_id": "554baacdf0ab2e639457894725b301eca212c05fe6db7bd257989b954c14edc5",
  "title": "A2 proposer/verifier common input bundle",
  "type": "object"
}

=== cphzyl1611/apt-experiment-artifacts/current86-r4/FA1B2de_Current86_BSO_A2_P0_P1_Execution_Contract_R5/05_schemas/proposal_input_bundles/6000008__S03__A001.json
{
  "active_authority_id": "36831020b75a201420bd5cfce97a54ada12d44246f56a7812455bc21b99f9477",
  "admissible_source_fact_set_hash": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
  "authority_scope_id": "34551e904bafa71fb2fb6db33162e94ad41a08eca6c747d429c83760e09c1306",
  "candidate_source_bundle_hashes": [
    "b4163b024a9349d8bc9a1ee4d57fe1542fbbe4a60609f38aacb311b7ddc1301a",
    "0fbbf9c82aba2b1a97d6955c3f480cd92841b00bf5c4f824553da1a029752639",
    "a0105dd0a7c4d0d980226682d9e9d662c6d16823629ae38580de25a724e37eff",
    "34463adc913e0f1da7014eaea41b04a9b97519f344d436ce3279fc69bc0c18d1",
    "d6b38601991893c217d8c20e1a6723331b6c12bb75606f7768998fa9ba2a24f8",
    "5cd4a99e9762ce04afb66c849a9fd3b3468cf314a175f60cae2214a355bf21a6",
    "f518bf60d302d1211380b691ad6fe86b9ea027e6c0acba4fe67e5fae4a2695cf",
    "82e3b8d9c0e742b1971b478f25860796d14bd26df27a177e672e08b8e14244e5",
    "209a2fdbf056f0dca4406ec5bbca8d3dca34b6491fda04c678a789f4ce34b5bc",
    "60e262eea4437140d5f47bb6a6fe5d9e2ec68aacddd0884e6ae46c7bf5af06ba",
    "6a218e67832b8d17d8ce71e488156b4935e3e2bf13bc788b9f709f1345d72e02",
    "c1a3e448bb8cdb5b70cb4d167cbe84379fee4bb5a949e24fb5814ab2505a7d3b",
    "a6a81a6efd527c46d3632ced9155fc61387e06da3e233ff0423f3077805ab585",
    "941fc78c289f82753a50d133b29b654a3e0c5cae5b98e57cfbaa1e5b8015da32",
    "77f11a85e664a71d6bd153166859f7f9318fdc301ea123c468a571576050b8b4",
    "f2646a2ea002d47f270164c422620d247b0b1defc42f50c00d1e7a24138bbc92",
    "be15b1999a9deee85b0ac1abea51e988ce021d64f236d3b1b237b5a75510cba7",
    "f3ac4943f3e96850cad27d8aca6318a9aedcc71a90f27b15bc144440dc9c7dee",
    "cb98df1c843df3650b98d854d1a7e41ffc50e02288cfd4545a84bec256957388",
    "affcb44e95198ce47584c3bccab256f0f3fdc415407275392d00f52c3cd02942",
    "800752dfc646c5b2c7bb7da7c0f7fe42deac44465c90d5d770783ac445b040ee",
    "0e70a4aa0ef657e72191d2d43a4e636a5d0c4f452ab93363149f0c67f1763a0c",
    "b019c53ab7930e5ba5d294dae5b2a7ce8b060f8bd69d6392412e3d5689b8b5c6",
    "97a321228735e30eb1c689cb5e7a33f676503965d64e3b12876ed99d9ddc251d",
    "cf680f9257bda3bbcf107ebbdc001074548b8b82c488886d011dd4a82cd9adae",
    "0ac7df99f3445f32531506e73b4d035bdd00f0aa400b328d24afe1c3646e64c4",
    "2d4e8c5ba1fee74ea5915492227c26e91b634198238fbb7b19164bf46ac8d761",
    "e8b64ff4876a6e841ff93a9a23351bfe99fdbca85236078255df69a47dac2d79",
    "f228f5331818786407217561c61a7fa5b9670b3be7a0f6e9af5153bd7304f2ab",
    "150bccb9281ab75fa133f8d3f3a383903ee1d733e7ae75a33e65092fb98d6e94",
    "078624d482fdb8d7f15fe376d95448f7d8b9dfbb1b0ffb43a2df625dede8bfe2",
    "c050e1e0b854595117ed86fb29bc484656330f703a67cdd30ac7a71a09b6477b",
    "284589ab79c82764c4822b014379185b894e6aa0199ecaa42754f343f35b84f0",
    "1f30fc18ade7e047431982c0a7408c9c0b514da3dc2c85bca4e9cd53864018b2",
    "f80c8f177e07fc41ef52465cd91d0793135da24a8e253133971c03e8e5ca2070",
    "bc0abc2b138549fbdf9d23365ad177c37fe619491fe9ca85ac68666a907a541f",
    "ba51c3012932770073ef31370b919c27f3b3816dfbfb8380e4217f4aec6e87a0",
    "02b3b99e98d321558921817fa672370fbdb7f8ca2d2818b76a5cee663b642942",
    "adad4e86b9182a3833160a023c1320b21021613cf48533a83ff8df6b2b5c3e48",
    "7b4009e12ab5074d50ee512d54e86848ab64e5ab8c8452bea5bcf291a1c6f349",
    "4b733e936e0391b53062629c9d1fc7ee7c4927c3f8f983cdaa8483b8db405353",
    "f727021e5eeaaf5909d8dab66727c2050e6a14a4dab6f57e8e4612df12e9bb58",
    "d8821ed8bfc3db826aef39d995f5d9ece1fa7aee4ef9c0aba1abf49ff06b3b05",
    "cf9eb742bfbe3670541dabe99fddae79a17af90148c5850d0220f946bcb2c444",
    "778c3bda6d192d16598826fa26bbbbe69a49770ac8d2966111e9d98200ab0e98",
    "57e7dd09053bfbc67ad142e4e7ec7cd8f201fb50345b5be2fb69d2846000a584",
    "6fdbcc79d85f37de6ed69a4aada803d2e084c7277ce028bc639e946c1bcecb6e"
  ],
  "complete_candidate_relation_set_hash": "d9286ee815f6e73cff8b3896b49719e2d30b5cbf6a178d11655bbf4a0d0fb824",
  "complete_candidate_universe_hash": "42e27294898e2422841eaeae4e523fc1f07e97b36db745a1d8110eca2978ef0a",
  "execution_manifest_id": "9a76ac35974fe15fcac5031dff26576ed4fedd28bdbb4aece6302f8a7515b589",
  "historical_output_denylist_hash": "f2f48a3142bf192c08cfa2bffbb722e0131bfd4a1ba55623caf5af72748b94c7",
  "input_status": "FROZEN_PREPARATION_ONLY",
  "proposal_evidence_profile_hash": "e24746c96c5f741cc35df8d992d93936911dd1de2ce7f1a0f00035cda3b33deb",
  "proposal_input_bundle_id": "fc4fe1735dede33b3e8bdedf7e2b5d07c0e185c3d4f2778f025bb06d1c050206",
  "raw_identity_hash": "8c4171201b17ed6275ede7c2214af32818e953e6900a2f61bed2bcb7010087a3",
  "raw_key": "6000008::S03::A001",
  "raw_source_bundle_hash": "daec81460b5bc347faf9843e8f1278999a72095e70c91ab1fc291651fd8215c4",
  "schema": "PROPOSAL_INPUT_BUNDLE_CONTRACT_V1",
  "source_class_fact_type_registry_id": "8cef6206dfc3581c3e7b6358bde7a36e90f4ba99078176cc0e5aff4b238298a7"
}

=== cphzyl1611/apt-experiment-artifacts/current86-r4/FA1B2de_Current86_BSO_A2_P0_P1_Execution_Contract_R5/00_lineage/r3_baseline/05_schemas/proposal_input_bundles/6000006__S12__A002.json
{
  "active_authority_id": "36831020b75a201420bd5cfce97a54ada12d44246f56a7812455bc21b99f9477",
  "admissible_source_fact_set_hash": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
  "authority_scope_id": "34551e904bafa71fb2fb6db33162e94ad41a08eca6c747d429c83760e09c1306",
  "candidate_source_bundle_hashes": [
    "c76be5bacfdb580bf72d63ca6b631a124d601c0b0b28ec117f183980624f0b3c",
    "3695432f94c9b9b425a359467745aff77b6a32e3e98cbbc52eda99868265a43a",
    "1b83abd00a8ad5610accd47ddd3660b22a8c0c8ee2a769cab5ef1b6b59a14ead",
    "20e45526dfa2433cf046f71d70206bb3568911044cade18bce39b7013c0cdb1c",
    "1401576fb8290edfd7c4be0dd0e07d4c6ca6cb1a37e5c4965337c8cf8c08fe4d",
    "cf4ea65e6a82b23bd573070ec4f0cd1cf48153bf4ba5d6659090739f610d687f",
    "a72280b9868d8a27c5381938e3032c75d3a0ef850a28553c442038b2eef98435",
    "81a8b742486640b360c369777c994003f2161d893cb11a4c389c9299eadcdfd6",
    "b75ad806cf3931ad396f4ed7eedbfc6fdfa6e74d6ca02478ca50a474b8dfc3f7",
    "e214a1f9771a30586989710be6d60bc27d51e9779876a0b5864de6830e7373ea",
    "a529f7cd5e2f969a76652ea05fcd414bbcf1b5673b6e71ed2f388cdfed23f695",
    "0ed78c4cceaab8953764569fe0dccc9b257278df533b7c05a035f84c6b894783",
    "aa6a92a08880e1f6c47e1f5f9ba52da8114db3e6ca2591c684edd2d24cba4f94",
    "3eec0eb9f71716c1a6343e912111a088e402de27f52b63fbad3df390a2437e73",
    "9bb0c11af4ebeb22ea7e73f4385fc85c9d310ad92a08844329b91d6679a38ccb",
    "7031d4396b40fff40506bf98a312d3aa2646327bd3bfaa8698ca99196919978b",
    "a4dad80559c34f1630177ae35813acfa09d85ea32fe3c7667e5debd4297f0713",
    "164639f4e26d13205eb9d7c86297509fa9224746c53590f951ba8762715970e2",
    "073aa8a1aac431b8c30dc3f33e2ce866fdf933745c1d31ad5acb66e90d27f938",
    "0dee21f8e93da8b6ed9ca0c695febbdc3c87580f9a7352682cc39223b78ad2bf",
    "9355815e26b1eb2182a17143dd8d087b5a61627a0a671c9bab7130f3d19afd5f",
    "ee913ee37ba7a6d839cf004352df3269f0004a4aef4ab716aec3d1de304b2116",
    "dcc0224eb0c7dd545de93c633ba999bf8e2b3ebc7e377621905853023b92564a",
    "d9f690d45e25c6429df62a8103da8ba2d9a7b604287c73eb8fe0368811725154",
    "18ec45e5ab5371358acbe2345aef740479a4378285e0f45508aa45b1fff8ff54",
    "01b504a65f85f8496b543b5d2316a6c3a8468d91eb2e24068c4b6975f42d3299",
    "c68b484ce2f652e953f523ed9c9c68a530c8a2e1d32ce75594a53d50a3b79e93",
    "2b023f1185266915c06359fb90e879f6d68c98327fcc04533a05de8d57ff040b",
    "4a4d278341166f86fb7912bafeaa4349394b7b6df5fc06e3a00df2e02aa34555",
    "22f9dbbfeb92eae311b41bcff8f15cfc771cffd94a4b5b47b26cd216a45314d6",
    "5c6cd9b038f254c7375b62ddc1aef1ea2c89544771875a76fd8b2c6c91ec3fc4",
    "87cdb00c25614420ea0a8cf045b9429ede0ba34e4dde75014b6a1fb79d98c8e6",
    "c60d06da2ea97ec7cdce7278c5e48fe454fb05a640ce7ebd6f3d1654a07090ce",
    "14b344af2173a9ee3352d127d1063d810e51094367aede82a71df76dcfb24d52",
    "0186bbebe13ba18fe928c9db799909076ed0bf178d6803b6f0f7a4dc47611224",
    "fe0a1fb56266a6ce39e720b76b6289f561048346e6236ddae49c575549771ecc",
    "3ef6398ce64d7200e5645a2c93dbab62fdfe708277964c4b41eeef4f4947a59e",
    "596b79419ac2833581f577862008854a8594859d9def87af693f34ce72b0ab95",
    "6d5a147afbf38a7d4d2210e0599b3f56ff219ccff39149443b7510686733019b",
    "cde04be9318552e4f4d7a50b993a10fcb23f5ee399986fa110f4160b5f82ce95",
    "e2f964e6906c4f3a75c6bb8e6deb78b1ab113d2f1c599c5c02ea13932befff22",
    "66fdb6547753da09a6ca8400ed2a6424a328fc2330aa896669379d9a7f3150ab",
    "62b6f601127d82e361e952603570efcf173a8506c94d13989c0dbf71a8812c6a",
    "c87023bc7b69affd97618ead5776723d466f7c419efff7c725cbfa7130a67bd6",
    "7f1acd4b44819234ff64eca86a43acf142ee9d0b54d5a83b14059cbbd76b3b6e",
    "c78bb2706399f6e31368afa997bddd357def8d983566814cb33e1c3f605321c9",
    "7e8b3d8755d1eefec366407672afc62a4250788d9c13a141e96df928e7077b10",
    "f00b6d2c5d3bd3fde66499692a1e8c2d134ed1de87cc1b94dd9115e496790b4d",
    "329096de9d68441f51d641f7b12191203d6e65b461e370a98cccb6d3d2322086",
    "8f310bbbe86b1ab8f2d5109dd263282ddf4a61a81d0d033c93d506145fb6a541",
    "9be0d207403c9643e0a769fb0a23c5d05d2b5c934ef75430dd2d21f5c52d05c6",
    "5843fbb3f76e4e4d328c41d1d03435d5caf7d4b09bb034ec43d23e9881b058ba",
    "685e8411530b330b05abe27084e015aa25b8814fd1e780690b3ad8ecbd68e4ad",
    "0fb08fb82e31b7fb49607826ad9932fd9d6dc3f0f0a63019cc132b70443565c4",
    "960d638741b8acfc9e1e037238613adf08e2464ef4bf30d369820ae7456bc407",
    "ddfde60a96f539a9022612ffd149ae3cfac3fbb5fc34b983f8a36d47b0e6ee54",
    "2461b982442ee6377a9f4718a454894aa28e6f88d46a68c385d7d1802d3741ee",
    "f1deca7f6bea7400744856e81f1f2af7a5fe14991799ca0f7ce110f0c906ba05",
    "71e8beabf37de384aab902d04e8676c7aaffd5302d3c2dd2a2e3cad6a7ff9f63"
  ],
  "complete_candidate_relation_set_hash": "4ee254cd242dd3a48ec16e8d6d72371e5695a0416fd2281067d624e02cd3386c",
  "complete_candidate_universe_hash": "8827c1995b6ca5f7713e6c39ccf5223542e74ea7b1d01e0fe8392ddf30324f34",
  "execution_manifest_id": "9a76ac35974fe15fcac5031dff26576ed4fedd28bdbb4aece6302f8a7515b589",
  "historical_output_denylist_hash": "f2f48a3142bf192c08cfa2bffbb722e0131bfd4a1ba55623caf5af72748b94c7",
  "input_status": "FROZEN_PREPARATION_ONLY",
  "proposal_evidence_profile_hash": "e24746c96c5f741cc35df8d992d93936911dd1de2ce7f1a0f00035cda3b33deb",
  "proposal_input_bundle_id": "f9dda1596561132bc5a6b5d5abfdf4398e57784636600cab434427a760e1f5b2",
  "raw_identity_hash": "d6424a99bfc1aea87eb229f5e6ea6893637d4d22bad34011305d16fe960eb1b3",
  "raw_key": "6000006::S12::A002",
  "raw_source_bundle_hash": "bd9ab86292de9c4f5c60e35b774603e5b3b16b5c9894a867ecdf83ab1281887c",
  "schema": "PROPOSAL_INPUT_BUNDLE_CONTRACT_V1",
  "source_class_fact_type_registry_id": "8cef6206dfc3581c3e7b6358bde7a36e90f4ba99078176cc0e5aff4b238298a7"
}

=== cphzyl1611/apt-experiment-artifacts/current86-r4/FA1B2de_Current86_BSO_A2_P0_P1_Execution_Contract_R4/00_lineage/r3_baseline/05_schemas/proposal_input_bundles/6000006__S07__A005.json
{
  "active_authority_id": "36831020b75a201420bd5cfce97a54ada12d44246f56a7812455bc21b99f9477",
  "admissible_source_fact_set_hash": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
  "authority_scope_id": "34551e904bafa71fb2fb6db33162e94ad41a08eca6c747d429c83760e09c1306",
  "candidate_source_bundle_hashes": [
    "1368b968fe0498282d0bce2d229c4e66968a53fcdc5c38223a0510c5aed93d4a",
    "995bb2b41d5f87b03de51c1cd19125416514ea7424a5fd9c1e871b6bde06fd6d",
    "c3c47a7728b2447739148ebc7633572bbf9cc7d7f44f47c7ba2efec5fa84e630",
    "c0b82da36d4b714800519a49a4076d0d7f7a1a1e91ff24357ee128a58a29cb16",
    "f1ff2b961eacd6eb737fe41081b9129f2b2a4cac983773a2e88eb71ab1fad445",
    "ec1145eeef8a3d6486dd2b0f0ed6e836ddb28f50935eb45060a3d561d737d56d",
    "d81a989e0fffa0cf82ee97a8921aec1078a66659648f6c373a2eebbbb300b4be",
    "dab3cfbfda5ba86a370150b74b583ed79921df1cefa25efc11ceaab44f19c6e6",
    "b3a01787fe561836014ed7ca63320daa8b557dc23c0de95f44872da524abf5c0",
    "6eb582c411274293dd29212e3cd581cf8fe5bd960436a11214fa2098fadace7c",
    "662fa3aafdc96fe1e33e060dc09ad10717cea0f647b8a92633a701eed65aa0a8",
    "1c99d575f01a912181331ee27445d49a7fada21d599c61adfa7803af84920210",
    "d45b3c3156f111463c2c889fd40b8920d97cdcd7028ab05de53f35d3f137d243",
    "3cb004cd4fecdd1e627a5ac0997787ba01a6ab834fb953fc232cfd410d8020eb",
    "5814cb0310fed8abc3b04699a43e0eaf1d3c34cca610e11642ccedd45acf17ad",
    "e46d1e5032a7f9878f8c733ad267fffc06ea3f9a468601bc8383d0b901ed9fa9",
    "cf2ef9ba41564cc4dc19d18f0873603a9e955df4f45095dbaf7e51ce114d4102",
    "a5263ace329637c07f86f19b3ea059cb93f75c7ff36bb39c7343df148e976499",
    "554a04b3a25886bb9fb80782aa89b9d7f81fc0e945c848d6c2d6cc0b8ebcbcd7",
    "1d93ee49c85684d4560193eff52e7cdd75aaefcb662c6619ebfb0f63f6447202",
    "f38b05017cc92fc7a0c208a32aed40183d19e367ab6de48016f0684a5c03917c",
    "dca1aefb63d61e16e916ac90f5455623325feacac59e5d6c88b61065fc66d2ed",
    "06706b1ee84819bbc60ef1fee8d7a45ea95f80b3e0e8b7083714e83e929524c3",
    "f196fd15cbeee79dbed64b40e293eff1d40fd54f7879f4bee69589e968f81e03",
    "6d4dddde6699805b3882d760d87b41cc762984436a2cc9be70d56251ef098164",
    "c4e835b25728f95978806f2d6507bd9428be87d7672f887558448e444520fa9e",
    "64c51e5e7ecf94d8b3275ee5a77d41c7b1061365c48a968a4d14cb0862c43329",
    "e446ea20dd0b0b40c4bc3cf4d32d3d879b4ad9f973c670abcc3d0e2c5afcf4ea",
    "be7ee199d2f9986a852e7940d868be8091b14575072a7562620ad3bdfd2d4ae8",
    "aa0e308e4e6f37cd32361c722229c7bed4524ed44d781874d6dcd8e83b65cbfb",
    "a7facb01b4e937e1fda89889389068bc49970755a4c666a7b56d391136a3927a",
    "0fea8ff81795c9af43b0f3107a74b4e8232ce13e00fdc7c9ce5628bbcaff3877",
    "8ae339580462543d77d262b162ec41817c0df9850f1ed59a12a3453b8b6e750b",
    "9edb20e9f36a3f5a65543c46bae936e4e331f6621654a673e1da5aee2db054bd",
    "526eea5b758b67b354cb532778713854b5167b1817b2be10b94201c82416dfad",
    "6391286988b8b164f0f949e386f30d0541e09bb990d892c1a8aabc860eb40dc0",
    "750721e77bc9a4e4601bcc76e044779125991410959de830e8f6b2bac662775c",
    "74909d795138b5a55f8caa99ce69a7beab44acbb6d1da0cbcb411cbc14ee8767",
    "499f1d7f31c8272b30bd2b43180e93617d491be2b9dc7344b05a6cf695c6aaaa",
    "9a8bc1f489fa319ec18fa068eb69ed768aa19a22be1339db922d23d53b7145f4",
    "f42d497febbfcd1ccf2e70943f3fde15147decaaed7f54c6169d7ccc8c22e459",
    "74138503165cb89a1c864c41bcf92c2871505e6c0d527288beaf746133d2a0e3",
    "19d4eb29663d2e3699ecde601548a850fe10ce387608f84b2a45a3e77f695e6d",
    "bd99efe866701766918c55cd6f154ae433da19ed36f9dd54d3d8bec4ed105b3b",
    "9054d87d518273990b6c203862814e9e90176680e482f2744c9f85358529518c",
    "8b95fea9af3e243cafa8f4ed6b59a6c04edb47ccb3a3f4164668e512455bba7d",
    "1885e702f38e95d5cb6453c3820efd3dd81365d39b8110fbcc75757f2501385d",
    "05bb98f642cec89632bb3c025cc15a1bc5761a0861fd0ec5d6e50c1b16607586",
    "5a73ec819c62bd02632f3eec66cfc5f58f93ee0b393c356eb573116900e81514",
    "19b86cc81dd4f807323db408e0d0d3833bf18cf5484ca4772e343d583490f988",
    "1b3f9b50d62d786987bb9242c98f0c4f317f83bcd911a7ad94fb343c23a290c7",
    "2ec1fdf18eba60cde007f67b7d3bc22cd2ae0c7a9e175936194228f6b097e4a0",
    "9497d760546b42aae6614aa3b7c5c72ad26e7c8b2f8330f434048328182603c9",
    "8ac4b5ec2887a809e31b24fdf40e2955fd716e9aa537d2b968d57e83a7c4c1ed",
    "5b5fc51b20d755cb05e69067b227e46a85f01060ea631c562042283b67577535",
    "959ca921617ab35ce0019972f2dd17e254610ae408c2b14cd274f2bc065fccb8",
    "ac3368bc9bba79cef5d2aac7a0c5658b72d45c01c645e8badfd0ddd6d9980cfc",
    "111ddfbfa4264071c66abc5ea52ecf2f80fd77f3cc5b0c377acff68bbcfa778a",
    "6866f423799de590ea6d9d3d53045d9700e61ec8c7ae39072a985eb6d9677b45"
  ],
  "complete_candidate_relation_set_hash": "9b2bcb627eb45eaa84950690150eb5105ec2a8227a5fe3c5141af2392f60688a",
  "complete_candidate_universe_hash": "dc0d7e8a98b151875eb271ae68d39302aa3ca1251c05d240c91a2959769558a8",
  "execution_manifest_id": "9a76ac35974fe15fcac5031dff26576ed4fedd28bdbb4aece6302f8a7515b589",
  "historical_output_denylist_hash": "f2f48a3142bf192c08cfa2bffbb722e0131bfd4a1ba55623caf5af72748b94c7",
  "input_status": "FROZEN_PREPARATION_ONLY",
  "proposal_evidence_profile_hash": "e24746c96c5f741cc35df8d992d93936911dd1de2ce7f1a0f00035cda3b33deb",
  "proposal_input_bundle_id": "458e101fd578fddd94568bad18f0b6651675c5d3bd2944de7823d837b5cfca52",
  "raw_identity_hash": "b33576da706e7d39ef753d486524a4d83b341109fe1d07805bd90d9ea6a5db22",
  "raw_key": "6000006::S07::A005",
  "raw_source_bundle_hash": "a325b9cf4d89b0eed43d9ba473756a6a0774c34d38e94a2e5b5768d6f3bf66a0",
  "schema": "PROPOSAL_INPUT_BUNDLE_CONTRACT_V1",
  "source_class_fact_type_registry_id": "8cef6206dfc3581c3e7b6358bde7a36e90f4ba99078176cc0e5aff4b238298a7"
}

=== cphzyl1611/apt-experiment-artifacts/current86-r4/FA1B2de_Current86_BSO_A2_P0_P1_Execution_Contract_R4/05_schemas/proposal_input_bundles/6000006__S11__A001.json
{
  "active_authority_id": "36831020b75a201420bd5cfce97a54ada12d44246f56a7812455bc21b99f9477",
  "admissible_source_fact_set_hash": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
  "authority_scope_id": "34551e904bafa71fb2fb6db33162e94ad41a08eca6c747d429c83760e09c1306",
  "candidate_source_bundle_hashes": [
    "bd882d2005e5284bcea9141df51d2ca8afcfb16db29d9d1535650f36d1121d20",
    "5787388f2c2044928fb026f6d5a76ba064a651514a0b7d1129e1e5312ec0b372",
    "00eee811bcd433ceeb31509f020e5acde3795d9efcd119615ff49f3e5aff7e78",
    "eace9e4b3edc705c1c1083b9ddcaf1ce8a9bff8c505e9ca1d0567bd07fc8f3ac",
    "1ec8a3d0e9e62688c628836204ba6f971205aefea2029bc17f1d5ed55970b8e0",
    "1a1257b9edb2b15eba0bb14bb97b3c502a12295ae12de39b23bec201a9c7d4c3",
    "c482a524efef52ab9fa45a13b34e0f1902e4841897b573033806824a133ee05f",
    "a776c368c9aabd6f64771ce0864e1bb181206b70a7c9b68386cf0dfe4002a629",
    "43c8924e88abd787507c3201cf60ebda940c04a067f3b17ecdbd8881a52adf4d",
    "d3c5abaaa5a2fb4d097e20ddbaa67d111a6a61cf368a9df2e14e49f7036bd6da",
    "42f251c7a9acf36f03031b43d76b6e514b93c043f9e6aeba4eaace74b6ed3ed4",
    "c1cc3376ff1a2dbe7201811c35a0280575cf14056ded901d4cd7af31b6e3a60c",
    "9681ed914a61794ebc536de741e155f74f722f3375e575fc2f647542dbc8c403",
    "b40736aaa92848d3db584bbe2c42eab6c3690a6a2414acc46bfacb48363fe071",
    "c6626070c9e67c563bfad2984587b3052a33cb1eb2812827469408e50dada6bd",
    "3ddde0440a8835bd2ce73899128b085558e8c0c257118c634cbefbd603faf60c",
    "b174a64bf72edb705f2f4c7d19868b342fcebfc6b0d7e2ad895706c937a82b75",
    "23da32afd7d3fd33bf2192358b6dd224a4ffdae0066f72c10c46fa6b98ca57f7",
    "0ba7f5e3f69e9c6b9f5a73bac0d3d5c9e835cb8426fb3721b9a84fd3ef885b83",
    "a76ffb75b0b9f4d55897f180cf556a08358b6d69b3c9cee6023c3a43cbc506ab",
    "57db23f984d4a802008d00a43408964f0b9619d64adc4f2aaeb0539308e71e95",
    "583e40687e179842cdeb80d76999307470bff229d75b2f9730678d5ee4929a7f",
    "9c30f47326befb0b28b52b4137ff9e2df45af5cc8b86adf6ea72535a6ed06deb",
    "3f16c46a997464d863bc6f92665c16c53b0787cf3b00c2f2d856affde461e4d1",
    "9aafa736266f0c50f4970f3f2b07e58fa7f232e2d5d8bf7552353834897ad95f",
    "36e9b1232551865cf27705ea850fe01f1d1882ff3f0c5ca6041455760695226a",
    "e1cda9913b3ae22124d06abd6cd519c62fe313198b8088c5851ec18bfc295984",
    "613344f55b4ec0dbc938b194432ed63b95c033543af3d12e91b0e2ee06af8740",
    "6ce23b19443179d8e33d6d3649a6c97b854c51a890663cad2be776a258c07470",
    "dc146f2ce65bd1b118d58b488563aab65f6d2d5700f8b65ddce97a69f204625b",
    "8d5db274f60450d77bad24560a29ba30c9a928ad72198f53ddd246b344da4a63",
    "812dd0dfdf7c1592ff8715a48fff6105249228959313d8602902e526638b27aa",
    "12b49442e530b2613c3a89267a0a85eb56d92d4941d7ee1e0b9bad3f580e0306",
    "2fe57c43c4344ea3b053ad2fe0bec72790ea3840b77584cb513aa90c2088a170",
    "128418f6483c4bfb45c18142b8e671a29c42afe7273dde8919611e27cd4f6f37",
    "c9ab2d2d0449a008efc38e7dfb104fbb9660987f866f810d4548328af971e14e",
    "0fe467702a702fc4347951e1bf3b442346239fec92a47b203fba4007cfb503ac",
    "5f5c4b5ea21d784f9e9ebc457887daf1cb1efde168141bb0cbe9cbe928b732b9",
    "ca3d9def9b12b381baafc05727ec6b9e10b5cbf5a1fbfb2660a34a1c8f6c9c35",
    "6d0e0757869e0876dd103557923feced2772d436e70f124773c7f502208ddbc8",
    "8c7b2f08f7aa5f6d0374a91a4ffe3b8659acef04da2623311c6759eecc5cefe3",
    "eabd76054a6673da52e24c0e6a1d1a4fa62e7f3d13b46dc9be055b228bd440d5",
    "24ec80fefe2ea6584cf1b4330b30171e59511fb432aa3dd0ab3b7c18a6769970",
    "91df036933f96505712060fab5e3c61483fef0edea659b30cef716eaff4a9219",
    "dc43ebfc7b935742218d83a89ef7076a1599c6fdea018ce0fbae8efa44cb9d8a",
    "45408c5bf14913ee96c0449b4328931157796383fcb6967f529f058db7488904",
    "939598d1bf5e5d18d547d647f7f9cf49da0a3950e6c94e406c5c3ce01336ac7b",
    "754cab007e4006e415456a88581dedbd879775a240360eb2229f950bd1f8f089",
    "cb3d42c9dfa0f8cf7d17fb480bc9f5e1f4926514cd8b376306ac58f82cdd16d5",
    "26572471423d44e11df56032944dea4d699748423072b0c04c73bce19b7cd0d7",
    "09bba58557dc99025fb5c991fdb47becce61d3d6ddb0eb55f94238f80de9a6a6",
    "62c99eb58b4cf13d59b3c9c778108de271658c67a8f50c8dc547a8cfdfe2baec",
    "916c9e1bcc3128fe8f5648f8a2376787c849f408a69b09d15b87c7878993e637",
    "52e80c9aa1a561af1fe1e358d6bd273f1524f23e2301cdf698d2ef77d20501aa",
    "b85180f92bc0f51d693ddee494b29cba2dfdeb85f1876cab73849fae835be5fa",
    "e8b15797cbc95ddbf03656d9c991e885df1f784ebfa1b47109c201c8b53c8ee7",
    "b86c9a5f1b7b62c578bb92bf87b63043b8cc73152363f13cd5b5856113b9103f",
    "f6aa6638b4ce1078ca0f64618b3bdd7c35a85f41185003caae39ff9a41c8183e",
    "dde06aa878f6a6a9ce6948e23c375dd2b85132ca75b0ccb0ca71626817c6ac39"
  ],
  "complete_candidate_relation_set_hash": "6e78af2dcb2c8f8d542701ae3361e497a793d237b420b8dca856815ff052a5e0",
  "complete_candidate_universe_hash": "5dd4331015a9050340e2f30fc6bb0d5623dee43d95c038556ed03c5d02dfba06",
  "execution_manifest_id": "9a76ac35974fe15fcac5031dff26576ed4fedd28bdbb4aece6302f8a7515b589",
  "historical_output_denylist_hash": "f2f48a3142bf192c08cfa2bffbb722e0131bfd4a1ba55623caf5af72748b94c7",
  "input_status": "FROZEN_PREPARATION_ONLY",
  "proposal_evidence_profile_hash": "e24746c96c5f741cc35df8d992d93936911dd1de2ce7f1a0f00035cda3b33deb",
  "proposal_input_bundle_id": "ccd332d47e056007559fb60326e6c4556cd93568fa54804335f57c66f968af4e",
  "raw_identity_hash": "a1ed63c4b6eb75bbee15a03fe5a4812bbe3216de9db988ed6db1d60775ff5778",
  "raw_key": "6000006::S11::A001",
  "raw_source_bundle_hash": "3c2fdda625c7327425d445be81969b672c568414d66307c5b255db169ce7599c",
  "schema": "PROPOSAL_INPUT_BUNDLE_CONTRACT_V1",
  "source_class_fact_type_registry_id": "8cef6206dfc3581c3e7b6358bde7a36e90f4ba99078176cc0e5aff4b238298a7"
}
