=== cphzyl1611/apt-experiment-artifacts/current86-r4/FA1B2de_Current86_BSO_A2_P0_P1_Execution_Contract_R5/00_lineage/r2_baseline/05_schemas/proposal_input_bundle.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": false,
  "properties": {
    "active_authority_id": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    },
    "admissible_source_fact_set_hash": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    },
    "authority_scope_id": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    },
    "candidate_source_bundle_hashes": {
      "items": {
        "pattern": "^[0-9a-f]{64}$",
        "type": "string"
      },
      "type": "array"
    },
    "complete_candidate_relation_set_hash": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    },
    "complete_candidate_universe_hash": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    },
    "execution_manifest_id": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    },
    "historical_output_denylist_hash": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    },
    "input_status": {
      "const": "FROZEN_PREPARATION_ONLY"
    },
    "proposal_evidence_profile_hash": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    },
    "proposal_input_bundle_id": {
      "anyOf": [
        {
          "pattern": "^[0-9a-f]{64}$",
          "type": "string"
        },
        {
          "const": null
        }
      ]
    },
    "raw_identity_hash": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    },
    "raw_key": {
      "pattern": "^[0-9]+::S[0-9]{2}::A[0-9]{3}$",
      "type": "string"
    },
    "raw_source_bundle_hash": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    },
    "schema": {
      "minLength": 1,
      "type": "string"
    },
    "source_class_fact_type_registry_id": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    }
  },
  "required": [
    "schema",
    "authority_scope_id",
    "raw_key",
    "active_authority_id",
    "execution_manifest_id",
    "raw_identity_hash",
    "raw_source_bundle_hash",
    "complete_candidate_universe_hash",
    "complete_candidate_relation_set_hash",
    "candidate_source_bundle_hashes",
    "admissible_source_fact_set_hash",
    "proposal_evidence_profile_hash",
    "source_class_fact_type_registry_id",
    "historical_output_denylist_hash",
    "input_status",
    "proposal_input_bundle_id"
  ],
  "schema_id": "554baacdf0ab2e639457894725b301eca212c05fe6db7bd257989b954c14edc5",
  "title": "A2 proposer/verifier common input bundle",
  "type": "object"
}

=== cphzyl1611/apt-experiment-artifacts/current86-r4/FA1B2de_Current86_BSO_A2_P0_P1_Execution_Contract_R5/00_lineage/r4_baseline/00_lineage/r3_baseline/00_lineage/r2_baseline/05_schemas/proposal_input_bundles/6000006__S12__A001.json
{
  "active_authority_id": "36831020b75a201420bd5cfce97a54ada12d44246f56a7812455bc21b99f9477",
  "admissible_source_fact_set_hash": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
  "authority_scope_id": "34551e904bafa71fb2fb6db33162e94ad41a08eca6c747d429c83760e09c1306",
  "candidate_source_bundle_hashes": [
    "3705483d894cd3f64c712af510bce1bece4ef56f5d95e1bea00b7dfb05509c3b",
    "35972062e7a1ca659cfa55f5e84b6f3d1249432ba47c8f7a2ee89714088930a5",
    "f1abc97e870d230d9e80965be45f0ae3b4bbd122a33418db2933ae447c912448",
    "73143a85ba76ec40f41860fdeb73bf099d1cde8d6075fe8d9f8f94a46552ade4",
    "c9f826fe02260de9980926ec5ad9f480637719f654ecb1a25a71f30986dffaaf",
    "23b3a57dd28fba21f32a0b36b90986b9eb4a4e1d7949a39a5ec61b02358cb327",
    "509072c391080ad8a46ff41fc3fd1d76c8265d949dba1b4db6dda0732be202f4",
    "4a0e850fd0fb166fa57f6a452b325e00017f13ffcc70a3055c7679726aa8035e",
    "bfa8be03443ac19e5fc313f281d20d35d3e2f8605ac23ba051827684e07e4310",
    "d9ad5a046d5d49d464051a2ebe95e632d2aa581467f3e0f195a39260cc6e0d17",
    "3d06304f133c598449fbb2f4542e189761fab785ba00f2e595b606ebae6ce83f",
    "3ba06965c7c76638b35574b8538c4f00f60a1b1f8ce450187c495e481c98ce1e",
    "380561455bf84a8d0dafc322f67e39f9f4301c909924b6f27bc276d07b4b0980",
    "c50318ec786a14f282a05559775fe05ccfe57cfae151fb7d4fc2c0879c8fd459",
    "c185e2762aca1ec96eea713c73b35eb6b9b6d6e2cd1c59765a52d11151727fdf",
    "9c85c1b08696f781bb425c9e99f08d7f2471b5597775d93fcda6ebfcfa74b7cf",
    "67552ee734e50abcfffb7a8ba5d60a52292b61fd8e072fc91a14346a96dbc75c",
    "319a2d43877588e71c749d70b8b17bf5fc39b1cf5e3a63b91c6dbc0d934f00f5",
    "7e0905f8b5505c7d9b9e40492ac08d90ab412a7ab48e666295dc42b2de5e0557",
    "0806fb5aacf75203e3be97b45a1e247a97f3d8b81f45ae7ed829c4bcf9fb951a",
    "b07d1f7b6b51848bfcc0212662a7a3e71bd8b14076d3c1570c2117c96c73fc17",
    "09297b07bba5fe7bcf24bfe4942ec05755ca7044fd39c15833f442582c554c6d",
    "dd76a8dfbfaab2e32b18ad18613b580db18a99ba1a0eda4072549ea2fd89ebac",
    "01546c49c0e4ef7fb5fcede63d01f64bde996c46949a8fd61a375237f7891e6b",
    "2b79865e1f92594bc6fd978f6d844ff4e1d6784727c82eb6ebcdc751c0ac4c66",
    "a8808a5b1aedb0bd24d87386a944bf4b1cde5fbe2dfa597e7f85c18b54f765a9",
    "982faa34f31d42365cdef83dc60ddb11e150a6f63956d20ffd11b624b2b7cf94",
    "f7098b300d1c8494ce195e7d06e57f5f46362d4733eb5d40921f6613c8f5f5b3",
    "6e669476de3b5f58114c78390836039d363e199831c60b321056c70820af7022",
    "5b12fffa9ae442d99c848e1f3d93f20ede9c9b9ab8c7134ecaa2b70e1e4b953e",
    "9ca9a880b9fda751b4d2db0a4a7b9b52105752be5e671d6bc55adc8f69a969f3",
    "b6bf564d922b38a17804c2bfe099d70935943d85dc6314df4e9413ed8a499729",
    "b068acf2f0bed10afc08d69d4619852659dec75347377ef7cbbb9e5d3ad29947",
    "2ccfd83bb4c52874d1ddc49b57febdfd7364f8af32dbd6b8351e32fefc27c769",
    "07215b8b22a0840c2ee747293898cab9acc2421efb117aececb5f88438415187",
    "0e29140aa14d6d1968e9e263f9f29999ac0303f1cf8290ad213684b4ac51ae17",
    "f8e66a62bb63716c47b8a5702b27e63b58aa4e2c13acd2d13978c3734f38e46a",
    "24cea5a2bf6cd2074cca91368948abad8335611127ac076e418c3f48fae574bf",
    "4cbd83dee6c88aaefb18e1a4e9d78b5adf31bd001ec71d1afddaf6fadd077e93",
    "a24f4a9b2fe97848c25cec1cf956ceaab21850bb45bec08db12ad3510b78fb83",
    "d25b566c29abc78b8a50f926600ad8f9cb831c03e85464c043592ece4a425af5",
    "4483116df9d1bd17dcd57420c1bc204152f0f2fe4b975706aa13b00c8e3061df",
    "d2176bec324f183e0e2c0a6d59043f9e8738c694e0bb109daec9ae8e3a16df1b",
    "521e63160975c3745ef23f4a9f77bf820efe0dcab254a20e6b5c3d4474154301",
    "ade73c27431409151e290ee84c0b5d49f7d861af6a2aba8eec1445b84021db2c",
    "388d98e619b5fd35d12354fe3662a65d8b6a676368397c019df0d14ecd134219",
    "60994fa502745e8bfbbac26bd92fb5297cc1107ebee14b19274cbcc3277ba6c4",
    "6b62c890c7daa314d1aa8878ce4f2f264c5dbdcf6530904c375bda61fc39cb88",
    "67517b7002da627106197cbaceb51e34a95a41105fd013a93e5efdc6c369236c",
    "b5a89ababf44ce097ae327376b87b750b9f28b77d35cd8e698494668e63a6a0f",
    "1c7b56c12ef82677ac1f3017872212fa8cec95e076c78325f9a1ca6e531fee62",
    "297f35c84fe7564705f539832df91da614b89b6ebfb533302f3cae13a33bc35e",
    "32ca5fb7ad8830e01f7537ce29d7d35094bed457c4103d0e3d5742026f63223c",
    "a8ed369916d18bcaef1ebab4402b71f1326159918296ed3135c557f456cecf30",
    "dedb1c07e74dfd63e0c30f0b62005e09d8d68a70727f06340cf715e51cfa9690",
    "e65287516c6ec8d54a3b87e1163c3cc05707c65c49c38b833dd0bdce200b65dc",
    "aa4e1d5e55c8713b61f71afd360e9a314adf351600bc9383dea12aae47ba3d69",
    "830d6e8e08dfdb3a36c3d2a44c3d6f94dfdc75765bc619c3531e1dcb92fec539",
    "3806880523b738c435d59c49d0f7b631ebd40895633fd2fabdb6d9f2f96182ad"
  ],
  "complete_candidate_relation_set_hash": "a05a0c49fa6cf9ca3341bcc9271afccf6160b86873162c254d13d8dad2037558",
  "complete_candidate_universe_hash": "99862cd3dd30af604f0d9936c786da6e0ca9ecc1eee82d1364997ae85075612a",
  "execution_manifest_id": "9a76ac35974fe15fcac5031dff26576ed4fedd28bdbb4aece6302f8a7515b589",
  "historical_output_denylist_hash": "f2f48a3142bf192c08cfa2bffbb722e0131bfd4a1ba55623caf5af72748b94c7",
  "input_status": "FROZEN_PREPARATION_ONLY",
  "proposal_evidence_profile_hash": "e24746c96c5f741cc35df8d992d93936911dd1de2ce7f1a0f00035cda3b33deb",
  "proposal_input_bundle_id": "f95aa35cd6653c7ed4df81ea7d40b80a0a21efffd83aa32771720e256fe3df12",
  "raw_identity_hash": "557c4bdd5b81639c3be969ceb5301ff6a1b9b87a02c18366dea006f3b0957839",
  "raw_key": "6000006::S12::A001",
  "raw_source_bundle_hash": "75d5f472a32693ea53d928383cf2b3a9da4ab1619579995ca9e3cca375173c6a",
  "schema": "PROPOSAL_INPUT_BUNDLE_CONTRACT_V1",
  "source_class_fact_type_registry_id": "8cef6206dfc3581c3e7b6358bde7a36e90f4ba99078176cc0e5aff4b238298a7"
}

=== cphzyl1611/apt-experiment-artifacts/current86-r4/FA1B2de_Current86_BSO_A2_P0_P1_Execution_Contract_R4/00_lineage/r3_baseline/00_lineage/r2_baseline/05_schemas/proposal_input_bundles/6000006__S02__A002.json
{
  "active_authority_id": "36831020b75a201420bd5cfce97a54ada12d44246f56a7812455bc21b99f9477",
  "admissible_source_fact_set_hash": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
  "authority_scope_id": "34551e904bafa71fb2fb6db33162e94ad41a08eca6c747d429c83760e09c1306",
  "candidate_source_bundle_hashes": [
    "11e3c8964ec42f0e88739b2cf557eb933896db785ce9b41e7d2531ea07058a77",
    "e51ab434490d027ee93122b61607c1cc1b49e8347b7a9e4f5f6925708eba3cae",
    "856be91fd594ab038b098346b12484da7025120814f4ed7f959016baaf038e37",
    "ea164729e8e80402d9668797b71345b3f1144968356ce8aa9002455d09408b30",
    "02261e1edc8907f728c173a546cd48506082f00d58051b89f7e07ca08be6dcb5",
    "cb3704f18e3c1548130ddfbbd8ac6885f8bf65b5c27be81901d25029ab2b412b",
    "6ae35330a17313e489a62c0371bacd9417b74c298f9e944383dbf2aa3b96c690",
    "19e00a76fc5069cd1df83eddb9049d63a0f8334bbf695118185bb518b02ad64b",
    "5fe199aad39e631ca320ef2c36f24b2e8558ac68334f84045d798986514bfb38",
    "f81a39a159db7bd572ebbfb29e14c5e9a8983a7906726b00132158cd45159569",
    "33dc27f4b546347d127d408ef9b288104eeac21fa4c72010955b733e2b6e4798",
    "d2c0e02c507eb372397c428457df06571298a5776cf3e332827fce4c95b3e0a9",
    "09fcfb9c4b5534cf17a8ef4849eaf0225e925f16d4b8ed2d6771d2567f656285",
    "05148f704efebbaa0a5b7f0cfdc947ff6839e0c8bb2ed6c8bab1a20aec1729b0",
    "a80cb7f17e07322b182b135d0be546a3006969a63adca416027b6efa9db36328",
    "10ada4708fc4a616602467693930670f81ee0f39c27a643ebb2d1e8071e54f23",
    "18db6a3a51370678a94d7053eeb52ccc662de3287d62f41a63f260c0ab28ee7a",
    "f2862c716ccce296c19ec155baa4cd00f5a09f6bdcad3dd577f6bd8b8890598e",
    "74235709ca32d5575f5e5e9b9c664f9393058e993bf73598d81e658de49e3225",
    "8fa88e52c8bc8faaa024297488a76307d35fc57a77f53c2df544433936284f69",
    "197793c7dc70f3e2e82145c100407f396454cee72097e6e2b02f48b90cd993e3",
    "1ac6db3fab05998741b61a231a8bb3f5e94f25d8e4c164aab3d9c4c24ade6b9e",
    "38c5b0cf4e0c21c41b3158ce72d52b68730f67026952ef7c70be156c6338055c",
    "902d25c8ec3fa21845adc5138b59929d0a09ad76a71f05e4d117a0da7f370149",
    "359d64a4d0c95ac000e2d75a6091f3a2f2927a28f51ee3911e97987fab2777e7",
    "05e0c8c5b82109a7d079a5422262d17a049e37230d5173aa265083f42695f030",
    "4c2f4ea6e2a37038db4b06c99d311ddff89dbf1ea7807304554bf1f27c3d437e",
    "a54e2e3aa260e0f43286e728ed99dcb5b60b7ac02e555cc3e8577d193dfb8c9c",
    "bd12be4c4b0d42cbbbb9cb4c519a8d7ee86a89de10b12c863b9e367c54d621d3",
    "9e5ac727ac6b680caa8d00c27de1bab0217d7525d2c54a6c451d0133f52d6163",
    "4af4ba2b995814980f9396ccbfdf595908831fc22c38d75b7f156a23e2101222",
    "4c873155c5c3d13b51c96d70435ea73536dc2cc12a8bc6aff35533606ae951df",
    "c94caf017c421a26c0aa68e11d041b85a8a7516f8653e73d5bf19d9aa895e6e0",
    "25d44cb122cd257acf983172526a493af994342011c17ee2afecbe9518c1f543",
    "a51d3939e3dc2c3b2764cad8502522baf3d003062cdcda60bebe97b9500a1833",
    "421b198200095ec09212d336cb89bbb53cbb16e2022c634026886037870828eb",
    "423a73b7ee897bdd5b23ec3c55682f94ca9f3dff05da27bddeba0772094ba3b4",
    "98bd132370cfdf3bd55cdbca94666fa32deafa8a21be29cb376b59bc7ec5fcbd",
    "904b2f2daaf6730283464828ad0b044fb6901e29c2417e2a633d7780dd218c49",
    "4fb82a3765a2fa6cca577e01bb5f1f7e4c9e43ba5ca7182f13696007d8d60923",
    "ceb2392a7c6362136611862f1c1afad73412814c77562cb78bf9ae53eab0a830",
    "45100bb0088bb55ed80763a6cad3c9e70196b1d7ab52f0145003a3e1eaa18e62",
    "c09f4d48b6878b71457b3140bbdd421db5318af7e9167fd6c9129baa1df67bb3",
    "eb3321e766bd07769d62818b54b7fedede74ccd64528f3cb8b0d4292ab974529",
    "b12545024c4fb1f6defeef14deb8d7dba5c2a6a67c31fb8d48a4fc9a4865f95d",
    "000d411c4a8963795f976067e5d1a790e11f52027b1c395e912d591b2b29d726",
    "cf9e05406f325496341c232bd86c423ef996c7e116d443264ddcb045e9a07d3d",
    "9e52c1389cdab25c8fa63dcb40fbe090126e761db34a62a3ef4c4c172df844d7",
    "19a02d7ce12c187e2e1021780702de919648401aaae6f36c87094ca0982c1f9f",
    "9f2e6d629e9669ad6c1ef12e89816a0584e4d475da14fc3102ee5bd4a4a9e0b2",
    "50ad9f521b360c76d39bea02da6f7577a2963896ee48336557c9213cacd8e08f",
    "d31ef9f9b9a803d0cef8b9b47c961ea28aaffd37acaf3dc853fe2a33e5a3753e",
    "ea4d32e2557c324022bafa372ed667a0f66fd524fce79c8baf3bbef8ee117766",
    "e9efd67e68823d959c16124b5a3d0d856dc97404d53955c2182e1793c02d0e9c",
    "169c28a5591a7f109c57a360211867857f82f1b1a2c24c5602825346d460fcbf",
    "003d89cce56a78525f90cd9985bc70812ad5ce536737bc01076b13002040c7b5",
    "a1214f62a502c30aff8ddd6c5a36fb37ddd4bcccb4d62e4b7f474e814f52e842",
    "10f5c43a86852c78ca8f5b485533440f08373b9c62a35c15ac45b8981dd67cfe",
    "6d1a295864189ad0c568625abf2adb8827997ef5ab3b08e14287877bb290ef86"
  ],
  "complete_candidate_relation_set_hash": "ca49d4ae7ed294be03ecfa8f18222e26e3f21ad11800d426d78a621e3be7f361",
  "complete_candidate_universe_hash": "89aeacc2b21cef989deb9454ef0fc4edb0aa0ddfe5c81d7fee99d7dd1cc52692",
  "execution_manifest_id": "9a76ac35974fe15fcac5031dff26576ed4fedd28bdbb4aece6302f8a7515b589",
  "historical_output_denylist_hash": "f2f48a3142bf192c08cfa2bffbb722e0131bfd4a1ba55623caf5af72748b94c7",
  "input_status": "FROZEN_PREPARATION_ONLY",
  "proposal_evidence_profile_hash": "e24746c96c5f741cc35df8d992d93936911dd1de2ce7f1a0f00035cda3b33deb",
  "proposal_input_bundle_id": "96948a449a29fcfa3a5787e0a51cf3ef94049b0463e0864b640cd6e395711454",
  "raw_identity_hash": "8e7bcdf4181250c188b3dd700f727b27844d46085acb3438ed1698411a6e7e3e",
  "raw_key": "6000006::S02::A002",
  "raw_source_bundle_hash": "8c58419d48e4e81b71ff09113a31e2ecf25d083b709b3161b17bde3ef6f85c77",
  "schema": "PROPOSAL_INPUT_BUNDLE_CONTRACT_V1",
  "source_class_fact_type_registry_id": "8cef6206dfc3581c3e7b6358bde7a36e90f4ba99078176cc0e5aff4b238298a7"
}

=== cphzyl1611/apt-experiment-artifacts/current86-r4/FA1B2de_Current86_BSO_A2_P0_P1_Execution_Contract_R5/00_lineage/r4_baseline/00_lineage/r2_baseline/05_schemas/proposal_input_bundles/6000002__S07__A003.json
{
  "active_authority_id": "36831020b75a201420bd5cfce97a54ada12d44246f56a7812455bc21b99f9477",
  "admissible_source_fact_set_hash": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
  "authority_scope_id": "34551e904bafa71fb2fb6db33162e94ad41a08eca6c747d429c83760e09c1306",
  "candidate_source_bundle_hashes": [
    "ac27c449a9142e06e055071dd05e71f4f36716d6a40d2eb53aac687e56a77087",
    "672489b247efc02fa0cab20c27f7ed39dea2bd8435e97ef2d08ba2003cd6707b",
    "72308571626a0382fcb6aeb394019e14f17047d5e0bb5557a84cd5b818cb9ecc",
    "a00a93baae6a0e9a90a65684c71b9a650549e72aff42b8bf202177ceb74dee11",
    "1b6e04de679028b74513d957bffd7fa5c1c110a021612725882d457e24ecc143",
    "be486d806b1206f7809b94328b1ca0b55323da8a9c4733e900218e8da6e9c149",
    "2d4e6de616d33dc8c8176b2e4c4bfe545ed86058502c4bfef689565c055d4fb5",
    "d0e77c3114699c0405aed1c0df180363c09411729b7488b09f7c1b35d5514107",
    "80a2cfedd3f2103197e4b2c70fd110799035ab096db84c460757d1a472ac6cf1",
    "704117597196fb2ff1f1003009690eac9e2cf0f08e406792d6e98d6509662529",
    "62aaf33d524b88b9100b0513e7845b6e96215a3a6f969b42b99bd2358d1acd55",
    "77a999f9da76d5af4af13ba4533eb544bb4db55e1bcd6d94cc142f35c11cda3e",
    "83e0add401e9b7a07d7af8d836ca51ab4be828b9a01674c0c3dcd7bc78acc874",
    "3d7108405dddf4ad640cf88579ce84149a6a80a58ebad46ac5cc8b0440d0efbf",
    "accfd12c140668dd13c3c1fe775627259266c03201d5f1c1ddd81cee66c6c60b",
    "1e95f0ce618a1f658f05c5a64707aaf3aeda6dc13f3ddadc1256788f8d3ad7f2",
    "f12acbb9156d0e85de81999dd4d0b603f14d96f52478d1e67bd955948796ce32",
    "257092d8ab647db171084a53379d63568e1bbcbaa42d40b2d60765644b65a5c8",
    "2f7be11ff66b7e94cf1545c58b5ea408429bf58eec34c36e0b47b394cc924261",
    "a73d0ea7bffc53f4b118e41995ffe7674beec73a7772b121b376a4f617fb1fec",
    "c688a10603dd426100e66067b79ea966dfc71b40783d12f1f2d9d90bb54af7a5",
    "22ee0cfb8db239fd419bab1795bacce7334fbf4ec2483f59571e567d854fd902",
    "804107061e206d152c49d88e46a72ac5fec768a770faf0ccbc6b1ac022540ce9",
    "65fac3d8c0aedded8b76cc41f143c816de7b2edf513f2fa66110e88ed497f825",
    "3a7957dce4fb1588db3c9a7c9151ebe2242c956b71806dda7432c25d3b1cef2b",
    "660c84229ba9ee96a2cb76ed669a30257a8b90d5f81391ab9d49339cfabaa2c3",
    "1b2e1287ccdc07eb1448775d0647e90b15e9b6eb01b0d7dd1e88feedd1daeceb",
    "54a2755499ce7de197299e927dae1c6aeba378e0c1d95aace2889298ffed0817",
    "465753dc80162a8b17aa7599cba35f06e58fc3a1749ffd9461877a4d4af2c505",
    "4e7ceb805097e8efbdec4912d4619c75a341bd27f43b4b9163ff2a25591e57d5",
    "ea2bd115a5b7e1709e63781d93495c005e72fd0e7e2dc2270321b7af46c75573",
    "fb927fe737864663395b8fa5fff541d95e0341b10e6bc1e9d7e4ab1360658e10",
    "e03c829efa19d1fc70fab850741d9bed730f46da8e1ed7795882cf3f462d694b",
    "d6b18450f9d285efd4fa08a06bad230a92de4f847dc6e4d575dec6f2770b976a",
    "f43a432523378ac531afd9b354a5e763f0903732d6bf9af5e4436556b59832d1",
    "24ab9913dd661dd50b61c80be70263017c4404773652d5930964d025fdc63599",
    "cee01e2ca9d967460ba90441a311f48222ad05bfcebdfdf482e66597dc7c2e51",
    "dc753b43a91e35a25ed647e00e8b5d2e1e69f851334694593e8dd863cece8808",
    "24f2daad066c144055a551c30b29cbcb7bbd145b1deb826d0ad557c1ba2e4ae5",
    "218aa1d857b346b75cf64cc7bc6aad3a50f40008b0ae333d36aa24db413a6b64",
    "2d58fa55d9090971f3e476f641b31dfa50cbd8978020d7a813851c9ad42f6625",
    "3c608d6e9441ad3b33b26dd50290726c4e0816295dc66c34f1e8699de601c0b2",
    "185371c167fb07077ba00edaa2e5d41613b06db416e6f6c8e49379a2620a81e1",
    "108ad76d14fb7ad36c71d1746951f4b38ca3660138412e431c6508f277b5c7f4"
  ],
  "complete_candidate_relation_set_hash": "8adc3542b5486eb21a74fb5a30e0bc9738936f6a5d62753bd62a7a158f241fac",
  "complete_candidate_universe_hash": "8896daf01d8c39208b1fac1c7acd17c1d13f1f807da043d9925542a25f929c47",
  "execution_manifest_id": "9a76ac35974fe15fcac5031dff26576ed4fedd28bdbb4aece6302f8a7515b589",
  "historical_output_denylist_hash": "f2f48a3142bf192c08cfa2bffbb722e0131bfd4a1ba55623caf5af72748b94c7",
  "input_status": "FROZEN_PREPARATION_ONLY",
  "proposal_evidence_profile_hash": "e24746c96c5f741cc35df8d992d93936911dd1de2ce7f1a0f00035cda3b33deb",
  "proposal_input_bundle_id": "3a6eaf08217fca93c95a84aa811ea33c3a751e40a10e4090185a9ef1bbf3527d",
  "raw_identity_hash": "4fe4bd098e9e62f8b7ee6df4135cfe61812374ab3a91c805133738ce3fd8d746",
  "raw_key": "6000002::S07::A003",
  "raw_source_bundle_hash": "adfca0ab67b83ad3be8f5ed45d9066f6442421bd3dffe0704e57cd28bdfa08dd",
  "schema": "PROPOSAL_INPUT_BUNDLE_CONTRACT_V1",
  "source_class_fact_type_registry_id": "8cef6206dfc3581c3e7b6358bde7a36e90f4ba99078176cc0e5aff4b238298a7"
}

=== cphzyl1611/apt-experiment-artifacts/current86-r4/FA1B2de_Current86_BSO_A2_P0_P1_Execution_Contract_R4/05_schemas/proposal_input_bundles/6000002__S05__A004.json
{
  "active_authority_id": "36831020b75a201420bd5cfce97a54ada12d44246f56a7812455bc21b99f9477",
  "admissible_source_fact_set_hash": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
  "authority_scope_id": "34551e904bafa71fb2fb6db33162e94ad41a08eca6c747d429c83760e09c1306",
  "candidate_source_bundle_hashes": [
    "950d66ad32d0e9358b747e0ed4fe254e605ad5896e920c76daca098934829d8a",
    "37232dd7b49c77bce85643a0cdccfb6e65241a7fd5589939506b19294e7fb08a",
    "68b685cf9562786e2e9ea4bf8abc545db1669e21ae04d4dcf23c6714dfa42883",
    "47fcb3afbd07439b435a87e7abdf027c57218b83ba460f096495eae6d6854571",
    "cbbee8ddac4ab3a464c5891117abb17e108170fe32993507b12300f94152de87",
    "09ac10380c8e0dc98597350d9baa7e0da68bac6e3e45cfc67c831cea503ebea3",
    "114b9ca974ba5c400f027c134592419df2bbc68d3ea44988acca54d9f79c3b5e",
    "b0a393ac122f7a324ab15cd27d96ff1274e279d50b23a1d34b33a03de2675ad1",
    "a65ead4cbaf1d718d1e5b94fe8a754d61888bd79c9d9f2123c53f6b3aa589a38",
    "d9c53b59d474fe0c853900591718d80c11da114d0ad919aafffbf111676aba88",
    "78e5f577b293ce452eb95e5138a9fbe10bf3dfa17527992fa05547b5a5ec587e",
    "280624eba2c1595cd387f8da395592450090dfb3efde5363d1db97ae0093f1cf",
    "4cce860ee35407582d0636ab7b3d7f4e7a1c65641f33c71f75000ad41de27e45",
    "8c7ca04340085ed108b633a1251758ac6aa9ecdab1d0b08a469fe474653ecdca",
    "1573d0bb3c109bbf65e938e0300a068fcf60b1c6ff4f3149c82a09c0512ac5ef",
    "71a54e3525561da12856e06e5f2ced1239bc0c959d404a71761e94aba9cc67c3",
    "cba587118c3596cd5d756549ca1755734f9860dfd1780d10dfd995ccb8d83f3c",
    "5245abe883137165958c0dd897f170b429cae481944c3b2253f028d5a88461e8",
    "a4e720031a103ca16b24ea8c266df2147a8b5441ece7bd3d3ccd6751cf4b6b4e",
    "53bae47558373f8fdf9983a2ed3db8d5897d8cdd2994b0d124c953301ff18b67",
    "3359b77ebd92a6d1edae1c194afc084245d96c2a204547b3f29f1bc1aa31ebe1",
    "dbe04298e841c028247981824c6b5ebb805a9f75210a7956916150a45d9aa7c5",
    "3f81a11274906cbc9fc052bcf9c684c65deb01a53df973c16db57342c534df20",
    "14fc3194a1d81d1f557a47cf96d61509be5cd56e9c784f4c6f7a7a410fb2f377",
    "a84511b1113221af8d9e815d212b4863f3fe39928ea4e52188cbe2a28952d338",
    "1f1d393aa34491ab0bc544bba261d0a3f6c099b831bb7f2b28155fd9cbbd8171",
    "0ad3e40d26e7c3fbbc32fc17559954ca39dab590f4efff6515ebaa71bdde42ac",
    "93642ef4d5fc7c65da911ffdbc91022b73940dd4cd8450f1aebadd15f19a40aa",
    "19753920e4cc5ff57974cb87bae6c9e4934f6fee421641f9786bdbe1979b0c7c",
    "bbac695886c03b896d0af616763185d51368c616853d07b62df4ea310ca56d96",
    "187d7fad319f2256062059bd4f23469c4c69cbf073d5fe67ffab690397d2b4e4",
    "52e89c57e6473eeaba2ef445682ba9d2f1b6009249c123f0fcde1d2268219b3d",
    "fc311b6097829e20462ba4aaaabdbf8109d16431e69ef9f6c5b400ef592e0a8b",
    "abe9ef4a5d05aed771083e903c34ba6a2f68f001dbbb33220b2aadae706190fb",
    "b838abaf6da78f1150d1bb1a42561810a92ebf0f43b5693260a4474a1d2d966c",
    "0e3db8441329b8f6bf5e29524324717e3a2f8b707e93a5432766374b9f33b5b1",
    "88997274225a07d252fe2ed82c975ff97e0a94ff5e9bc0204f696da5a65f9fe3",
    "46da1bfb3e0984cb29307d323bbf8ce67d166482e2da31396d3fafe2d4e932cd",
    "58cdd849c316564c9d726ce7a7fb90473d6983db07fa2ef077d464a48bcf2dd4",
    "888e2cefc96a151799a13963a0f74caf69217b23326c0174158f10f1a0d9755f",
    "cd5d595acc8f4464583b268af6a969f0bbd3a75dec8c23e8390c494d0ceda064",
    "c71be36da351178528c63430d2cb14f88e2a2298b0684fdd31d008863c5933b8",
    "dee9d45b55a0f496f8a113334c94d1a59cd2f472aa14d4bc68cae9c7e22fff8f",
    "725dcae3ace298f2a504ebc359e6b610d5313e034e7d43e311af5d54eb8fd9f1"
  ],
  "complete_candidate_relation_set_hash": "00d849e1f63c2ed721425ec13583c4055f99bb4e1d1c980be639e27af865e6a7",
  "complete_candidate_universe_hash": "34f4eddee895b0668909897b7a43c3410f8e626b5944ed7b29ab79f8ad181150",
  "execution_manifest_id": "9a76ac35974fe15fcac5031dff26576ed4fedd28bdbb4aece6302f8a7515b589",
  "historical_output_denylist_hash": "f2f48a3142bf192c08cfa2bffbb722e0131bfd4a1ba55623caf5af72748b94c7",
  "input_status": "FROZEN_PREPARATION_ONLY",
  "proposal_evidence_profile_hash": "e24746c96c5f741cc35df8d992d93936911dd1de2ce7f1a0f00035cda3b33deb",
  "proposal_input_bundle_id": "fe59055ab0b1e866ba6828a4103e7228796cc23d5c09c2c5bd04022c56d0eb90",
  "raw_identity_hash": "226f7855fb37f5f35345cc91cbeb3e7223747416ab47df7a756938795fa3fa7c",
  "raw_key": "6000002::S05::A004",
  "raw_source_bundle_hash": "39adf13c21e854a322c5cc4d515eccf01478594df2cbb168521cbf026c08d637",
  "schema": "PROPOSAL_INPUT_BUNDLE_CONTRACT_V1",
  "source_class_fact_type_registry_id": "8cef6206dfc3581c3e7b6358bde7a36e90f4ba99078176cc0e5aff4b238298a7"
}

=== cphzyl1611/apt-experiment-artifacts/current86-r4/FA1B2de_Current86_BSO_A2_P0_P1_Execution_Contract_R5/05_schemas/proposal_input_bundles/6000006__S07__A007.json
{
  "active_authority_id": "36831020b75a201420bd5cfce97a54ada12d44246f56a7812455bc21b99f9477",
  "admissible_source_fact_set_hash": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
  "authority_scope_id": "34551e904bafa71fb2fb6db33162e94ad41a08eca6c747d429c83760e09c1306",
  "candidate_source_bundle_hashes": [
    "77adc2172f385faaad889725b9eb756c88faf8a64ee26af1eb37ad1fce689e9f",
    "6a52214674dae327eb17047e30a2184fa177880d3f24ca7b47b25b7e6da45487",
    "4519f318ddab83e6240fc1911b5b1d4e1eaafaf8bf078012077c97f5208dd531",
    "14d7f63c92610f1090cffc9ecabe583a79d72a433d27f5a0bbfce73139397b90",
    "a7aa2b1a3d1b00f1239f26d5325e16d74a51e9d2977e1835149b727f283cb7bd",
    "a07bf491ae89a2c1ef7b0e8e0026486fc6bdbe3ea4fc1196a09d10b0c5d16002",
    "a947cad74fb568065061c6478599f6ec04d2f087ec055dc05b0db3cb459dedbb",
    "b10c17e92db6e18c64ef3a918fb27037136eea6c1f2bef7ca8b52b02960c9539",
    "6056ba6a53d3351d3deb38ed546d37dafb5da48ee4723621e3c5d51d94bfcbde",
    "bef5bc6d76d5c5ae6450436e32a1d3c52e1b6242913abbf151a5ff4a252dc012",
    "a15262dac438cd3a1cf85b05a2100c884dea9879cc4638972c599b3bc9dbf08c",
    "f02830db5949de94cf1b726cd79cce229d0a072c80dde26f45034bea967d64f5",
    "dd1411756eed80d6b422cf3a23ab8f90815a417c2c88d8af1a00a37cd0733ce6",
    "a25c484a05d71b29fb7967a1beb8046033d642ab649b691937cc42d0005ef0cc",
    "21f18f5931502fa1037d17bad2e96a5a623af4c4c7a70a592980a8a9d989a27f",
    "689affcd0f7a6657cf8aef1133bba349946bf78f283a8b78cf7e47f740352df3",
    "a48637c63ca3ab0bfd6f8f32bcc76d4c626dadc274b2e359a3430c4c296f3b30",
    "c55d35abbd2d4602da8bf288a9e6bb3e955b7cd07490e2b708840096c2b94065",
    "14997b3fbcd10357c9a981df97ab78a5154a8e6f01fa8b386b892eb885dc681e",
    "0edff2ef6b658ca463c5c0d71eaa2caa9908297050ef34220f9ee1265bc0630c",
    "effe4f08f46d9e955786ba3bc727d86a06b63fed7ca0df133d8e56246d2c92ca",
    "eaf80122f70ae9bfdc1d79508ce7aa0363d9f02469b4781d388b07ec2273d389",
    "5c66467441a2f44f899952685ef22f4be8ce873cde6cb86b9fef273483396114",
    "d096cac76572fcca1510afbd60319a7df70ccc0afb3303e4e78a7638196a8760",
    "38ed724cd8a70b4a89cf9a7dad9972b428f27eb4d1d1c43d95be97ee0c415b30",
    "6427edff69923958522c4dcf7929d573b342509800760c2ca8e4600ee8134426",
    "8fec3aca96dcad9d2785fb364f328787f610087566a1aa76a78fc080271c6178",
    "ec25eb9d817545343d125d6c33e0db3ed76367fbe4f2cadfc02f853b8bd98704",
    "04294ae83be124713672eb8958da6567c16ecd8be2d5fea932adfcea4fd2eb5c",
    "f8e6b93e6d24e525da8a6d5fe2f28f0594bfe98122304c8b25df15b76b1c6c23",
    "2f7e7479d1f7f0d79dff2af1e7475c91c8c829fc0b24f0e4c59992ad6086e74d",
    "16a2332cbd1a3a73142b43bc0b4fe3c051cc7cb848206c8d4e5c7d9ee661cd1a",
    "0b2be67e67a8d1e29a5ff37d154dd211f24b560c2a3f2b895fe55ccebcb6ac23",
    "4d3fca02c7f572c594fc67dd97e5e765eb0ecb5716afbf721fdd56533c877c3f",
    "4516af53ec282cbac9dd201f4a7dfb14c65b15b6db00977462b15e3de2919d5a",
    "efeaff25641793912197fb1ce32e9cfbad9c7e35230e7ec517fd07539e553e0c",
    "99934619dccb5c0d71d5eef3697ffde2de65012f1e5ca3584ba5dbe0cc5beac6",
    "2be04a1e50d2d5626d5f7d2d518dbe908dca967bb6a63fcefa27dca6a7bf1c96",
    "4829dc901e9b725e3a64d90ccd7d400e242a0e6937ddcfd3a251771a2fbf1ed7",
    "2fec4e0f8e2ccbb00a0f30f40e8e92cc66c55ee11554204a55c68e44d9406d7a",
    "91708342f734391197e98a126ca0f92381111a7d1c59fd904934003d51194660",
    "7f3512c78115007e08a2fabb7f642d92d9a47de64dd2a7fdba03865552a722e7",
    "a551018fcef6985e591e21659d23f8f808b727efd442c8f55219b1aa108e9583",
    "602f5035184a7bea6fd30ea3fd8f94d833821bd00bcf18d3123a6fa296359cbf",
    "6f07af1b736760081bacf9c155e959f8f7b849eed97c5cf22408564c659f8802",
    "60ca852de9b82a84732e8283fbcc320a45a503246612a3a8b4558781e29648f9",
    "78118489eacad82392e338d1a5ee136e48f45d8b3aded82896ed9281a9050b3a",
    "399d2822b9f19744a907144e72bb488f0898798422e5bcdbe739db348e15e9fb",
    "be88bde24be789ce913c97e8cf92f28f2ae3057edabe7a129ffbde9912922b05",
    "98085ca67af027ef0648faf5e8479e6324ec74eb4d0c7a10adfd6634cbf00cda",
    "0b691e7c573608bde8aa7c7572a961aaaab6a0f321385d554b577b0bec881008",
    "281ce738fbb8e7ce380e36cb1fb9582d318224b3928b6d4921716702f434cdd1",
    "4b36b614f8682746d06cf0ff4f2a008c73c2b953dbe0d8fd983e9f2b7fdf80f0",
    "825a07f35be95fb45748d8d783a4acbf9d44bd0da78a44e270765dc96482acc5",
    "ad475d28572c1f3ff30b175bdb7d94b651545fa951ff15a7df8897d2e9a3802d",
    "b3f3bd5b01e72b254aaaa69a3c0debc513479bb1c146ec6b41fc270d91fb37fb",
    "574b7af570da7daaf89904864a2e304d8344a6c3267fe1d4a4db1db9b4f73bb0",
    "d2025d4ebbef3de30988315f5c63da5bc4bc88ad2a2c18a4a35c23120b04d47c",
    "2975e66752dd629f230376dc44b3fbdd2496937c5f287d50327edc42189b6b29"
  ],
  "complete_candidate_relation_set_hash": "a5f39675f0dce100b7f5839c9641137ed386303554f4ca35c0fb33fa1ec43ab8",
  "complete_candidate_universe_hash": "1b2688e5aaf01e699b4eb2189e5eb87b39952872665521ab0b0039b42a90c28e",
  "execution_manifest_id": "9a76ac35974fe15fcac5031dff26576ed4fedd28bdbb4aece6302f8a7515b589",
  "historical_output_denylist_hash": "f2f48a3142bf192c08cfa2bffbb722e0131bfd4a1ba55623caf5af72748b94c7",
  "input_status": "FROZEN_PREPARATION_ONLY",
  "proposal_evidence_profile_hash": "e24746c96c5f741cc35df8d992d93936911dd1de2ce7f1a0f00035cda3b33deb",
  "proposal_input_bundle_id": "314c8133f59fd003ab7ececa67e2515440fae3dee583320394accc58cd10f695",
  "raw_identity_hash": "4c3c0eecae1174376d5a23a65c2859938dc410db4a71be8e13154f593788e4a2",
  "raw_key": "6000006::S07::A007",
  "raw_source_bundle_hash": "08acf17942f090f59d7a360fa5c07c11bbc27f4029ffca819dd937273c31eb4f",
  "schema": "PROPOSAL_INPUT_BUNDLE_CONTRACT_V1",
  "source_class_fact_type_registry_id": "8cef6206dfc3581c3e7b6358bde7a36e90f4ba99078176cc0e5aff4b238298a7"
}
