=== cphzyl1611/apt-experiment-artifacts/current86-r4/FA1B2de_Current86_BSO_A2_P0_P1_Execution_Contract_R5/00_lineage/r2_baseline/05_schemas/proposal_input_bundle.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": false,
  "properties": {
    "active_authority_id": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    },
    "admissible_source_fact_set_hash": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    },
    "authority_scope_id": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    },
    "candidate_source_bundle_hashes": {
      "items": {
        "pattern": "^[0-9a-f]{64}$",
        "type": "string"
      },
      "type": "array"
    },
    "complete_candidate_relation_set_hash": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    },
    "complete_candidate_universe_hash": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    },
    "execution_manifest_id": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    },
    "historical_output_denylist_hash": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    },
    "input_status": {
      "const": "FROZEN_PREPARATION_ONLY"
    },
    "proposal_evidence_profile_hash": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    },
    "proposal_input_bundle_id": {
      "anyOf": [
        {
          "pattern": "^[0-9a-f]{64}$",
          "type": "string"
        },
        {
          "const": null
        }
      ]
    },
    "raw_identity_hash": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    },
    "raw_key": {
      "pattern": "^[0-9]+::S[0-9]{2}::A[0-9]{3}$",
      "type": "string"
    },
    "raw_source_bundle_hash": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    },
    "schema": {
      "minLength": 1,
      "type": "string"
    },
    "source_class_fact_type_registry_id": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    }
  },
  "required": [
    "schema",
    "authority_scope_id",
    "raw_key",
    "active_authority_id",
    "execution_manifest_id",
    "raw_identity_hash",
    "raw_source_bundle_hash",
    "complete_candidate_universe_hash",
    "complete_candidate_relation_set_hash",
    "candidate_source_bundle_hashes",
    "admissible_source_fact_set_hash",
    "proposal_evidence_profile_hash",
    "source_class_fact_type_registry_id",
    "historical_output_denylist_hash",
    "input_status",
    "proposal_input_bundle_id"
  ],
  "schema_id": "554baacdf0ab2e639457894725b301eca212c05fe6db7bd257989b954c14edc5",
  "title": "A2 proposer/verifier common input bundle",
  "type": "object"
}

=== cphzyl1611/apt-experiment-artifacts/current86-r4/FA1B2de_Current86_BSO_A2_P0_P1_Execution_Contract_R5/00_lineage/r4_baseline/00_lineage/r2_baseline/05_schemas/proposal_input_bundles/6000006__S03__A003.json
{
  "active_authority_id": "36831020b75a201420bd5cfce97a54ada12d44246f56a7812455bc21b99f9477",
  "admissible_source_fact_set_hash": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
  "authority_scope_id": "34551e904bafa71fb2fb6db33162e94ad41a08eca6c747d429c83760e09c1306",
  "candidate_source_bundle_hashes": [
    "1093fd97641b990361a35b84dfbaa4f9d159820805b59d30fd4152702913f4fd",
    "7f94621cbacf0d719dec2340fd7fdebf730acb5f93309ff6e34c94aa427c16d5",
    "5c19a8413b439b81ecf4ae4c31cb4ed2aa1134b938b7d7a577e28c4039532424",
    "23189c3bae3df8f6a7d89f7cfe5925821d738e4891ca8aa78a67289e7aa12b3b",
    "fd5d7c8caeaaa396f7baf90c78783e8ebc5e1443d2643199bd349251290ac7fb",
    "ac9d32ce6e4792717417e7e10d5891b6ff577f9b7c5151b45f8a093963a3808e",
    "5184d5b5172a76f32b73b2e27174f3ce3eb1447f147bfac2b496c0c647d5284d",
    "603de0ffbe0550ca2e79f50ee77d9db542fb54cc27dc43c3b528a765ba8cfd1b",
    "be3ec0f5c50e77ba24b8b784e29fff132aa420fec645589af34252e5c5691c55",
    "e6ec9b5e8f9df22fb52995dfef88128be594c6ae8f6478ff0275e41a68b823bd",
    "99b629e8c80e40c31a096eb6c13345c95500d245f6e69826e999b2309c1fa84b",
    "dfed2622cb908f2949eaa6bd021426cc4955ec465d33370c7e3683783a805994",
    "19a67c4ea3450403f070287ec93bdda2df9f3e4e8ff6196da88790bbefeb2a51",
    "2ea7df2fd40485717c5716d42ffc941c680b5aa2f9962bf8a2d039aa8634cb9c",
    "692dd88c3bdbccbb3487a32dce41e52e78411199b613ce49aa357ef33d86ad58",
    "69089cca082d489f667db1d71bd929b6b0ee61a83761467ab27e52ecb7d45b18",
    "158af3e39d3fc7a21ad8bf78072931c86c06d674aa4b5b27ab165c29126f5713",
    "9f02accba9837f8fb7918e9348b173f2d0927d471bb10acdb7cb7d889932aded",
    "ba982857f1162965440f61086287c4037c1a6e749f3dc7d4ac825653aeda55fb",
    "d527e86c81a1e756f52765e51281547c9fa162e2da95879390b3ff7b68489360",
    "9420f04552a7544c69ccaeaba979dadc1903c8fb3b63e2731c67a2d810f948c7",
    "034923103197d8d29c1a318a510fd9537e5a129315b7201f714fb8cd1416565d",
    "36314a67d2df73440337f24391c42e9d92f32e0f1c57255409688f0d3c1807cc",
    "8b593fa7ca65121d7617d5c855d1a1bf20adf3c4f1fed374148c495b632efbac",
    "f78690b495daef362dc658cbb9499a9c888673de2d107e5baa216817f00f3f17",
    "54708268d112ecc3cf261484c70aa0db150cf423f28f11cfc52dc6206473fd01",
    "6c410525219666e6439cd8aaeb8cb1bf9bf030ee2a834685a4c279164edc2155",
    "2405a02f9f8f4843b90d0a72fee3c6b3dd580c070b246f111a4147091f594fa9",
    "e4686ed371a07177e7f289bc870cfede90e724c677f270fa4ebac1f6bf4597c1",
    "de04639caf4c2013ae11206c63d32d961305980ffc29e9545a32ebe2cf02b96f",
    "86e51bee57abc9a3d10f90cb5eaa4df430bbe5de7f6df07f868c6c3435991423",
    "7585479be1a52e6bbb221a8756292a5692181c14e554518877515d19bd3596d2",
    "12349ef827c784fca4dcb81e1d17c6995a00c1547ac05c3212a7dcb761bd958a",
    "4aff07265c3277bb066a93aacd869056f22bf08cf8ef1e4774dc7fefadb94cb5",
    "37b4510c81c1f048704263e04a28a571d879b075d40dd0b706968bd9b9125280",
    "682f3a46a6460cf51bbaca868cfc69f2cd21431a34ff01f4430c4be54aaa0b97",
    "ccb57ecff86d1d153554bdf24d0904c2386be51e8d8c9172e7f330e9225b60a8",
    "9ca4b41f8db36ec0521a71e021e7b1a65c67dcdb4d5febbfe2af75ba1f5c5e60",
    "a6c1f9d0e6987b0702ac552fdcb6986d0f8f5a5187ece05bb8116e2dd7dc5941",
    "914e7a3ef16804557bc01b053c8fe91b0c1735f4159eed2fd36b3d3c96a78fe0",
    "c90ad353698fa2a061eaf67f9d1f497998032dac1d9b090e160679245cda8f4b",
    "96347014795642fee18d719ae09280290669be3408eb70735c28ce584c80bc46",
    "db187bf75b57798d779d416bbf4922af5d27e4fd165e5d1fb2e4fd73d690f69e",
    "fbfde1f2940b64fc8f955336e4e700964ae296d3deb574a0aca490665a936b66",
    "5aaa4db0e7e7cb4326551fc97af1e2a50cb83b9235e307f43d7ffea96a1b5b27",
    "3ca7729e2782bd49731ef92a33235181f327644ab35fff2a1fb6d2b251ff2e4a",
    "9198c203f7bf4e649670401c785843793033c256545f20ce57011c565726af7d",
    "4062f4677dfa05cccaed39d51bbe0b92715667fc70db0dbcbe884660461fc0b0",
    "e756716064ff514c4def4f566277ce1ff716cef7ca437bc93322b686db1b55d6",
    "aa19a698e6713f5c0914a0c2560a7b1df3d4cf53e062922b71228f9e03486e74",
    "ad321b69612585156d65ccd913ab88504db52db32debeb4f770c38c1850bc62e",
    "437c4a9b38168fbbba426174cd9ec655a77a1ed1ba9e80f3ba5ac6727b341afb",
    "cb0ce45a6abe7767695e0caa522dc586e9e6e1a6e2bcba8121aa943f9caf190d",
    "66eed05843cff6008c2169c470c3aff2b0055dcaa2211005c774bb8a322d43bd",
    "ca9ef869d5ef805cc6512d4d4fddaf31fbd7c40c28bd27c2b0c4f1f67048afbd",
    "69bdd4e8837d2f9e747941c5bf27297226d02ee753df9f444c723aec2d0da677",
    "a5a4060409640956a9361b51c82b56bbc93b3a960fed601bcf68d9bb0da018b5",
    "46053c535b0e896abd1ee3e2428c7e7b26ebb9d1765e596a2743ce710d211217",
    "aff1bdbf6a75ea2e071672e0709894af62467f29063bbb94be6a5375de5d2629"
  ],
  "complete_candidate_relation_set_hash": "02c91ff4402519aa96db85460d95a3ee96600cfc0f8aabc3ae7f424d0c80a90c",
  "complete_candidate_universe_hash": "bd96fe0d0dc1c00b8ed14787be138c1c72a924ef02b83ffaf9d17d0697db1df2",
  "execution_manifest_id": "9a76ac35974fe15fcac5031dff26576ed4fedd28bdbb4aece6302f8a7515b589",
  "historical_output_denylist_hash": "f2f48a3142bf192c08cfa2bffbb722e0131bfd4a1ba55623caf5af72748b94c7",
  "input_status": "FROZEN_PREPARATION_ONLY",
  "proposal_evidence_profile_hash": "e24746c96c5f741cc35df8d992d93936911dd1de2ce7f1a0f00035cda3b33deb",
  "proposal_input_bundle_id": "ce4d78cfe2a318d0e0c4d06252b05b6e5876e170bed498b67d748d32b1e76ba1",
  "raw_identity_hash": "20bff7c4592b096e89ed35293773132764f40f9e7d2591b336caf33468ccd429",
  "raw_key": "6000006::S03::A003",
  "raw_source_bundle_hash": "24ed45fa32bf3ad8a4ef7149036e37048311145cf54e4e59c984724d80b1761c",
  "schema": "PROPOSAL_INPUT_BUNDLE_CONTRACT_V1",
  "source_class_fact_type_registry_id": "8cef6206dfc3581c3e7b6358bde7a36e90f4ba99078176cc0e5aff4b238298a7"
}

=== cphzyl1611/apt-experiment-artifacts/current86-r4/FA1B2de_Current86_BSO_A2_P0_P1_Execution_Contract_R5/00_lineage/r4_baseline/00_lineage/r3_baseline/05_schemas/proposal_input_bundles/6000006__S09__A006.json
{
  "active_authority_id": "36831020b75a201420bd5cfce97a54ada12d44246f56a7812455bc21b99f9477",
  "admissible_source_fact_set_hash": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
  "authority_scope_id": "34551e904bafa71fb2fb6db33162e94ad41a08eca6c747d429c83760e09c1306",
  "candidate_source_bundle_hashes": [
    "9d1d451d07a5b76105048f19b20f4ccba7b1fb8c38c92f99200069de32246a98",
    "8a417177fc3c69955651eb0d65b24ca705476fafee47a5bb297d5774523db70d",
    "5217e6d49b6104f1b6e387166fc1d421a50e86d7c1b0f0b87b149b7c4d61825b",
    "1ba9d1c3d27a252dd1de3c947bfc9eb28424e9c4f46c86651ba5be30c2503493",
    "bf4766afe4ca3442b44f40091fdfe42c4a715fb7ec3ea3e7ac01145f11ea137b",
    "1c8607ab21ef928bf8ae9459d02566fb0cdd341aa721f12b9d2fe11ca037e379",
    "f9e3bb0b945c29ded1907a86adcb18173f03bb65843591e265e5a3ebd36c80df",
    "01ae4f5254a946ad465b6acee9c63a0a6e92726d99e9d271f14d8d9a584a3ff2",
    "4381ad79bfc7a74394d6c32dcb4211df9ab3efb23e9953680ac11e4047405879",
    "5eaae419742d1d4999655fce892f20884f712ffb78c843a3f504fdad67fd57b5",
    "d03090f77900c575b232fde75cbc110090f16cb050f22071d382e8fb5d010b91",
    "f075694fd8fb554a851541a64b26bcb86c5f276ed2c116661e2be7a25a4f0fcb",
    "636ab63d4f1fb9083abdd8744d4817fdb0ebd3faff372f8239865ce15ccc99dc",
    "4a6e7cb5ca1cfac83574a61007c1ebbaff29b8c7b7a3b322d3210f35ab5b123d",
    "401dbb48dab55f58cd54ddb0a468e69f1b5363fecf4b2a354fa3fa1802eab07e",
    "26ca14d270e351f7e7853526e3cb8e22204a3e5e78129562c5f70d610f7b3547",
    "a04f4a97218daa024d277915ae150a413247710713eaab100e5b9424c853336d",
    "138ee9f911c75f47be933701972fdb03474ff618868b5b79839557e0949cfe19",
    "ce2b2932161533347d0b5248c6cbaba0d11a6e8be05b52733664e2f95d08eaff",
    "350a844c2bb85da7bd343121902f5b81cd77904bc72ed46282f2198eb323a521",
    "373d565b4956d7ef38c65e3a1446210db9957d023848196b0c078a7d1407bed7",
    "efec11698a493fd646c50ae032914782338abedafbf33b23de99adb19f85a444",
    "8ed81041e23bece67ed0e5a390554774f316df43b9c45854d528b0333af15ecc",
    "4fd7f43f60b76f85ec6bd4fcb26fffc620bdfa5fe38a189d178ab65cd18fe6ce",
    "c27e5f27d0fea05f381ed3e63e06a2b338aee10597b0a4153e57774d914a9dd6",
    "83e6ef2697c24e75513ad1fbdf555cb626053a5ffdb4a842e5b9ddc7486ea4b9",
    "e53d747f0c2219b688a713ae41548b1fa58afca890cf526eaf7640b649110a38",
    "be69fe7972802551be1a3ba600fc27a226adf07a2b48be53ec7e983cfc620f94",
    "18414cff39aef526e69c472571fe43147aefd4c87da3bb6097392464d2265936",
    "510d7c77f939f4ea4605035d0909d1218f98f6a98ca79d4ecf610090d6222c81",
    "1b93dfa5465a135f8a67f9bc6516273ad31d7cc764254e736812a77210cb30fe",
    "ef2dc1a0a4b6382d0f6005d8c9a63bdb4c3ef32194eb72224131696103f8bc7b",
    "8f7cc14d7c0ba3ae0c5353edf966f9d37037aa363f6a4fff0a15b5d72f8f1663",
    "a494b38222c499aa931725c1cfd99063497395f4540e381737977433a27efe02",
    "66c34ce9c3402824152de09287c246907db812f74797a05831176d4168f5d3c4",
    "c5ea1c3daaeddf2fa8c4ff5e51d4f12b3fbe797aa02492638015a377b05b94e5",
    "71be4aa8359a227b076406eca4a4dae70f5e293f0f30cffca844515e557ade27",
    "2b5402c0116445102cbd448af7507f13d936c64f4e0b3725da09511ead965a38",
    "e4531f9e8ddcb43ffb38a1868afbb2a89624f45e744e8a17597e0119e84dddf5",
    "01770d020279a1dbef4986ac46a087cc85005d541339b2bb3e35fdc6d0f1fc8e",
    "a1186898b31f4daa169c99c5ed704c00f9d1a29f3a31a1ab3ae50ef20e36b3aa",
    "afd3c3058226e117a4b1b371c62dc033baac4269bbc18694396a8e3292de73ab",
    "33bb441025f2d91d6efe1354f21b7ecf2e55c84cfe63f9c6872c681f38f55e7f",
    "1d41feecbc453ee8518470df2b50c551643ad9f1e1de79cd8cd1d9cd90f4b894",
    "5cff8852b14a6f7c509626599410656eeb993616f1243f2fc415851fc0ef5930",
    "2437dd49201cba24a9b82065b8ba68486e263463d772bd28c41c12428378a87a",
    "6e951fbad35ad01f2667a28268cb985cbd34ebe45419fb5e1448e578bd0425a6",
    "78627ce33aef8b34960c56dbe9922551b1220ec841c624b31ab9f17fc6104247",
    "e0b793a0385a8c0ef162552eeca78af42e3ecbcd74ea84e864abd94c58cc061f",
    "889f4af58b3d4ee14636f8894e01658c066d30fe49698750ab7d6b4fed10fc5e",
    "1d238306ff07bcfc0ed642a21fdc64a314e885be9d7fc2c0828255208babd9b4",
    "7747b189662a3fe890cd77e355fb11c1c867ad3a641f26e2c5d2af3bc7596058",
    "c27145cc23c7a3268f6a1b3382dfef085713ac537a02a89075fe04bd941a226c",
    "edffa898fb070ec7b03a141bd174c092e79e536d6e5fdaf04bdb46a49b240543",
    "a255d2b69a1087efa29e714899b77057aca8731a43bb0a9f50bc045c218824bc",
    "8e09a2288b533500cad181a7ac6cff635d5c03cacd2e846d1b5bd3e851bd60d5",
    "8e05ad22103f320136869c4e1d0e0570a8421c42013acaeb14f20903aee2a7a8",
    "2e326839b7af2c6d60d7b39c43ead752ef880abdc0232153e0e44e279a6ae729",
    "a61233355709e8938e2686df8201ce0b2c45eb42b8df991d8d30bbc0806b9334"
  ],
  "complete_candidate_relation_set_hash": "6a0ae48fa2276da756c37fcc378d5f81a7799583efac65ca9d5d418e4237ef17",
  "complete_candidate_universe_hash": "73bf2e2ebc3b6426e655a7f1479513999cec9fe0712d47029cbb832ff1a7170c",
  "execution_manifest_id": "9a76ac35974fe15fcac5031dff26576ed4fedd28bdbb4aece6302f8a7515b589",
  "historical_output_denylist_hash": "f2f48a3142bf192c08cfa2bffbb722e0131bfd4a1ba55623caf5af72748b94c7",
  "input_status": "FROZEN_PREPARATION_ONLY",
  "proposal_evidence_profile_hash": "e24746c96c5f741cc35df8d992d93936911dd1de2ce7f1a0f00035cda3b33deb",
  "proposal_input_bundle_id": "146c9634feff9339d679cf7a10efdba17e0a8c013e76118ee6cf1f4c5649807b",
  "raw_identity_hash": "f4313bff0aa948b28c6a84150105eca5749a7b4b778d30312f5ce80080b5c7b4",
  "raw_key": "6000006::S09::A006",
  "raw_source_bundle_hash": "397604e77e55def23d0aba5f8c664812dcb8f70f729e42da57291900d8b10591",
  "schema": "PROPOSAL_INPUT_BUNDLE_CONTRACT_V1",
  "source_class_fact_type_registry_id": "8cef6206dfc3581c3e7b6358bde7a36e90f4ba99078176cc0e5aff4b238298a7"
}

=== cphzyl1611/apt-experiment-artifacts/current86-r4/FA1B2de_Current86_BSO_A2_P0_P1_Execution_Contract_R5/00_lineage/r4_baseline/00_lineage/r3_baseline/00_lineage/r2_baseline/05_schemas/proposal_input_bundles/6000003__S06__A002.json
{
  "active_authority_id": "36831020b75a201420bd5cfce97a54ada12d44246f56a7812455bc21b99f9477",
  "admissible_source_fact_set_hash": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
  "authority_scope_id": "34551e904bafa71fb2fb6db33162e94ad41a08eca6c747d429c83760e09c1306",
  "candidate_source_bundle_hashes": [
    "3cd6e831314354c1affcad707d54c6bca5dd4700812e57ca1e3508f6a8ad5f44",
    "a1bfa3df6bcf11236280d21eef9b2ec0015dfec158acfa8cb185ce16cd9bf261",
    "e8bbea034d7e89a8b95d42e0487fb0c0aa2ac5b2002e9661ac60793f590d217f",
    "abdb799befb7a37189638c3ef06aa533b4dada0df22b3a1f322ee0a100d09179",
    "6f1b7ab9a48ab3eb7a01a879fdb83c84e1e7ac12f2cc21592b5c2a2506e52890",
    "5b297ef9e4ac95ea93c3ab1e107fd1096c49c1e63a28cad9df87e9d2d9985918",
    "3dbfe312c1eeff793db52e4842f611894bd4bfeba34599dbcbc57b056b8d4181",
    "1c9771d437a651ff4eb616c35445c224382edf97a9eb37c3478e9106bce9fc18",
    "dc2462b6546e3419197d0321ca5a19fe0f1a3255e9f4766b678a78e16f6e5c6c",
    "aa8319cc80a7d968d2ac82efe4f24772bf80aff8bb6e484a3ae29028c764249c",
    "5114152a6cc5f65be4873f28aacd8362b530042b8557a6ea2be351408d5cbfcd",
    "55095bb8fc05948fc5baa64db96f48cde97256e635f0dd49da25a1c20654ec91",
    "0e52c7734f8298a37121c39185cabf1e0929caabc7aa9832549208cea8b88ca5",
    "516725df2304b0c08cdb0564ec72483747472e0d0ee815227f74fdccd53156b7",
    "68f3776b801acfc9ab017e023f9b7610cab9585b0b37b420c81b3ed50f61d796",
    "0e16d2688779371c53cb8290cdbdf6cd0a770efc2537d011dab631a5e24b8cc3",
    "1f07eacbce5c524008b018eb2e236c2ac5a839a084404c7892862dd1c51d730a",
    "5f9699b2279149a010ab69df692ec6d4368c6abab8c18ed1da8c76f29e38ad16",
    "3e8493a0932097e1a1a8773c12f9be5fcca8aaa100f4a9f4dd744c038d741cc4",
    "82a048dd7b3a9ff686610310236700290fbdd90a20655602c9f18acc43a0e298",
    "f30a187b6f2718018a67f2d684e95dcd02d0aab23dcb3fbc1981ed8cc234253d",
    "578a89e518090f28497cbedb18cf44a71fff5f5a5749384e6813496e9d546a63",
    "7833e9d539377ea039296551157265201611b10402b95d7bbf77095fdbca7d67",
    "1fd07de56e4db651a5da175414cd08a3b0438e799c487ed171ccc6169128c699",
    "0e60451b637d0c3aa4805803c8050c51ea420993019cb9f0d062f7bf0df8a01d",
    "3752b048d38b16055a8020f979528b3ecd3b8e3af06da89b570d8d8169ce5f44",
    "6259394dc56608c9ea7fd8884e194cbe4e5d007e8d1cba894bcf68f0bc79340d",
    "10c47ad23ff1d4dbd2df989b2b28786f3336c03ef4c57879a2149acaa179ef2e",
    "c8c42ee0d160c90fa0678581d1aef0131682ac5fcf0602155c450e9ac070ed7a",
    "bdd2bd1288c76f70e49aa6134482bbc5c4330ae1fe75a7ad1e75dc7b64ae8c71",
    "06a7f501803637a47dce0b67277deaded51ea5562a9584f6362bec33abe59013",
    "e12928fbb0e11fda6a3c8af8efb3afed7cd584862f5895556bc07e667cef2626",
    "38c9419b23d4d340f57b92e53bb05ed579db59a966f05c686de720fd91e250a7",
    "2c4b484d99c659c297c0d046d6c338d849853ef45838a6a2491ec1b314df435e"
  ],
  "complete_candidate_relation_set_hash": "0e13c04dc6640cafb7a835db017c330cb88e453d3f981efc08b865fea7dffdc3",
  "complete_candidate_universe_hash": "6b045eec1c5b62e96c70867cd00184cb431d1b38d5a39024fc9b4330cbb3f672",
  "execution_manifest_id": "9a76ac35974fe15fcac5031dff26576ed4fedd28bdbb4aece6302f8a7515b589",
  "historical_output_denylist_hash": "f2f48a3142bf192c08cfa2bffbb722e0131bfd4a1ba55623caf5af72748b94c7",
  "input_status": "FROZEN_PREPARATION_ONLY",
  "proposal_evidence_profile_hash": "e24746c96c5f741cc35df8d992d93936911dd1de2ce7f1a0f00035cda3b33deb",
  "proposal_input_bundle_id": "03522a0a9c5a236579ebc704337bd5fd769440b07c97f61ba2f46eb68e65dd7f",
  "raw_identity_hash": "9b123a65d77304666775bc5b7f5de8092f73a81506a2be212002f7cd09f109b2",
  "raw_key": "6000003::S06::A002",
  "raw_source_bundle_hash": "ba83a148c61558f0549ac995d66befa5f893bca62d4bcd2a775689f4c2c55ff1",
  "schema": "PROPOSAL_INPUT_BUNDLE_CONTRACT_V1",
  "source_class_fact_type_registry_id": "8cef6206dfc3581c3e7b6358bde7a36e90f4ba99078176cc0e5aff4b238298a7"
}

=== cphzyl1611/apt-experiment-artifacts/current86-r4/FA1B2de_Current86_BSO_A2_P0_P1_Execution_Contract_R5/00_lineage/r4_baseline/05_schemas/proposal_input_bundles/6000002__S09__A003.json
{
  "active_authority_id": "36831020b75a201420bd5cfce97a54ada12d44246f56a7812455bc21b99f9477",
  "admissible_source_fact_set_hash": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
  "authority_scope_id": "34551e904bafa71fb2fb6db33162e94ad41a08eca6c747d429c83760e09c1306",
  "candidate_source_bundle_hashes": [
    "00c1cb8e827ff26ce3ce32a8779183d8f532b2c58845a3f9c68e8d76c939c877",
    "2b47f197c1db63e4501042a0bc8732cc7263e4c3be479c444fef563527b8331f",
    "41bb5d89487df7351f69f2a4a3514e2fdea2ff1bea6b1a5932d22ecfd4fa8644",
    "64079277e04c9e598aad65744c9925bc453a5bbabf528afc821e0f42d13cb658",
    "dc2dd664df20c90dc6459102a94ff672b6901099b123cd6168ccf0022ad87c60",
    "bdf939d4d367e52fbe215bc53c5afd1178cd42f4f11f5b71c517944c32cd0bc3",
    "693cef940b30ba1c32112ad79c81bc5503b5783b7fce9e50ab90d151e15c631a",
    "1f6a35f1b1fa288706bfedaeffbe938af653ce51d3370010036d9cbcbfc3bd6e",
    "93454904b516d60618975e9937364e43e813953b7fd525e47d9416dcf863d6e2",
    "48fe2a4204bab34536b9b86a77b585a3baf76fa79905a20d8bb05841a965d43b",
    "205fb870275e6cb66b1d4adafc95d8657d7b5e25095216b6c079532f3b289a5c",
    "ec8dc1f1d40bb59c25adbacee6a0714605a66f4089afc43f22c0d3228f6bbaea",
    "9c1f7af83fb762e81297854c164f577403d505b99ef529b4cea0485e0b4e0744",
    "b23f8557935984ee9d5814a1ee2700da94a340c400b457803aef7b3d083a5d03",
    "67213741a6eaa7fcb6a4ba6f827a9b06a86978e23dc766b1d083d572a5d19d94",
    "b8df94545159281f2cd472bb87515d3ad49a580b39cb94396b66cd7ca3d3c88a",
    "de6c906da07669a1747b41a2d3da79f481dab667fedbf17bac100d2aef276670",
    "92de564cc200480f0cae097c9dab513adcd6f99b5f9e6ce532f449e35db70620",
    "694d1197ff6fee8f3af909f1cfd203c67560c78ba3a9260a5aa7562755a6f45b",
    "ec515ba22366cb3c1deda81fc90394701b0545efa27af0fbf1fcc11834c3967b",
    "20c01f41b804bde5bbfef7e7f103c00f4d811e18f4207e668361fb15ab62dfe5",
    "7b6fa5db97b93eb7edb8bbd120260ba57a68a8b70a6337e4e66416ac00ce792d",
    "b5e5799ad32ce98950127895812e4d1fdb29e5d94a24b0cd2251a4296080bedb",
    "1eb627b757b98e94734d8cbdaab60cd045b7beb47fcdfde6d028f9e9ee4cd8ad",
    "fea2899a96ebf1386bc7e7ef944cc7b49dc5d1769efed0eacadfb981dfb39491",
    "f726a06f01d87fd99eff4bb196401c550593b213cfdcaa686cd1e11808179821",
    "f7c2c8a34a061bd3ce2c37eec9bee72854492f7cdd112c1835e81b85ece01897",
    "5ba760969c4a4365e1ea223e6ab326e26d3b2d1198559cc4b6dc0ac5eb0819c3",
    "18c839e65ddb1c4652b7dd766c900df320dc17c411f526e78fa32aa70eb077ee",
    "9f0e97ba67beca1596da301e356fde107c32844922f666270eac1b2c2b14ed66",
    "1e79533457007d5fcaac771c2d8f4cca53eb37db65f0a830201b604ee0be2bc1",
    "f99ce5084ab1ce40b9dd320a8a93698590c600eeaf97f67d70117b657703c29e",
    "f26bed2e96b430b2802024b6633e00aeef36ac2f1504d37c5f8002c9f252006e",
    "6c605cd244c2502dcf176d94d9b2c08711769c1d6cd7497afb650c7c623c0291",
    "4217be8230e696cd6f38536630c0a59ef2898b38b228768b3a11fa9e4af8f6b7",
    "7c0948a01ffad46f7b2832e528f7ff7ccd771f3e00bed671778009b6ea807e2f",
    "f3802aac61af6253770640d43222d9406ac24fda33c0eb6ebb91301f86a19e6f",
    "b15b6bdb1bdc44a6fbd1d6ce77e0c0d66b837a70a063f87d7280e7d41b8f8144",
    "b983600f950998577eb32f0724bbb2246c5e0dae58513ddac0119e1b24138b66",
    "9fdea2a77cf9d4e73f395c1eb701719f6c95e9c634c74e3a5e19884656af26a7",
    "6180c25e46524ff26914e123dd5fe9cf6168ef1e434e9602b51f26b53c0e73af",
    "2636b27a871a7ed790d5ebc72713dd44c8a4acf799e145a55d5983e8cf45044d",
    "ae8be4cacd95d5cb3c719384b2c8b5ae3932f442c061c73e73f3df56e648e317",
    "0308de33d90349cdc79bd344fc7c49871bbfe02f7b91c4bf7f826078b4e3ef93"
  ],
  "complete_candidate_relation_set_hash": "94fc51ae1196d176a99db27e6265d484c02e90bfb887c3781e88874f2f7674e3",
  "complete_candidate_universe_hash": "506b5f1d019cb35a3a563433f0ea8d22451855b7f0c9437644f25762211f8574",
  "execution_manifest_id": "9a76ac35974fe15fcac5031dff26576ed4fedd28bdbb4aece6302f8a7515b589",
  "historical_output_denylist_hash": "f2f48a3142bf192c08cfa2bffbb722e0131bfd4a1ba55623caf5af72748b94c7",
  "input_status": "FROZEN_PREPARATION_ONLY",
  "proposal_evidence_profile_hash": "e24746c96c5f741cc35df8d992d93936911dd1de2ce7f1a0f00035cda3b33deb",
  "proposal_input_bundle_id": "10c68e663180e5d20b224dce24dab237497d8bde3b062a27fc6bb06fa17b281a",
  "raw_identity_hash": "39a446c39d6415e2a0dfee4e5d9db59aa40656e38691ff0f4df4f6ef46c7095e",
  "raw_key": "6000002::S09::A003",
  "raw_source_bundle_hash": "e7a68b5284e8c4f70987a7ec1305061b9d4f392b6f487c3b05605a7c54dd4ddb",
  "schema": "PROPOSAL_INPUT_BUNDLE_CONTRACT_V1",
  "source_class_fact_type_registry_id": "8cef6206dfc3581c3e7b6358bde7a36e90f4ba99078176cc0e5aff4b238298a7"
}

=== cphzyl1611/apt-experiment-artifacts/current86-r4/FA1B2de_Current86_BSO_A2_P0_P1_Execution_Contract_R4/00_lineage/r2_baseline/05_schemas/proposal_input_bundles/6000006__S04__A006.json
{
  "active_authority_id": "36831020b75a201420bd5cfce97a54ada12d44246f56a7812455bc21b99f9477",
  "admissible_source_fact_set_hash": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
  "authority_scope_id": "34551e904bafa71fb2fb6db33162e94ad41a08eca6c747d429c83760e09c1306",
  "candidate_source_bundle_hashes": [
    "e6a4f1f4693472685d02d47347d749267f956f2a0060e4cdf76903f7545cf2eb",
    "fd2adbf64a43bc5bccf0d0b175b68c6115804cf9db74ffcfb16e2f526e92ebf8",
    "cadf234449f0cdc3bdff11a89541b11511ee0a3284a444319bf35b4ca5a66ba2",
    "ab589f0f84a25c9dfe430677c7e63ca24c45ea67cecc5ef89a98966cf534804d",
    "a7b27f930b872f9269210eca82eb1a530a5afff1b2ff380c72509807c150622a",
    "cd4a7222cbe8083af9c13251ceb73972f2fdfcf8488837a562485c55af6e7eb6",
    "e16527719d2f6b653c0982aafc1232e6431a087b4838c44856776a4a47d6fd12",
    "42227be3cbc1b8e597c58b81bf914ea8011599225d62d71480d7b18346bab7bc",
    "fedb5289dd934cb395ace49fc93c69f4eefd45c787a7215e3ffc7b20497d3ce9",
    "a3662ba009dbd17db677bf49227d6e213fbcdc5dd7b221e8a45f84c07b931414",
    "94f2facfa534afaa4f0ebe5cd3166e54e4cc83cd500feacf1eba65f0115a4672",
    "11c02e562237311ac8b91139a04f50e87a101f85ac52c6766de136e43e9426f5",
    "9713465ab8fae9a05c15487f911c0e290f342bdc5d0f45b829351174520a2654",
    "4ce5112eaef534df0e0d74147ea3725b9e1456d476edae633f12961d1602bf45",
    "cdb0d43560293dfaa45f9af82517e13e9ee23dbf42876e371f16699e441df6b5",
    "e2db369f1f6d8a75b30c51cd82c44b0c330f4f83217bf9b789478b01a09b5bde",
    "d3929fdf71bc8f46c2852bcf1d094e7d93f11030cd928f50135eb14d06674a13",
    "0173aa9519e426e2033d062e9d234e4dad05039c0535050a79c32cddd7d80d13",
    "e947133a3c1599a77b53871fb51d5bfebf07a8ce685ae075734917b10d5249b7",
    "5d1d8810cd0703269e40a42249ca256fbe04447a2570ee5fecb8d0d2a2958844",
    "713739c68ce8b7d3775380f4f0f8a375443c2d474290ae9ec5ff2d82d6d22da7",
    "9b2d2e17ca6d401512df7855676b7f41d82e9118fcd82e622aee9fb8213c51e4",
    "b563426dddfe6d0c25938235591a145bc832e9851ffaa5060599712ac23089f1",
    "4117e2e7a508b002d73b3cc0c15d72b10521b5e1b585fca79d2f8c775e69e908",
    "aa5e3193bab09235f2064dd7e681f022ec5fc77ad24263ea1169fb83914f2ed9",
    "4666007276f83eec7967696deef44d139d2ad41616d7788a0a27684222812955",
    "51f02c3c252334623dfea76a3c9bb161af6735329cb851e16d235c3d590e769b",
    "36be7d33707121cdb6cb8851e7707f08e7855a3c6ca98f5af70636059e193f64",
    "1249428891ced5a4c0ee15fd0b31bc29389c8838185f78a628f56e0fe57cb4dd",
    "7badd83ec7eef1ae4346151214fe337921ad95b3868ff059f37f0c60a9c7e17c",
    "86231e998ff33b7501ac50ad63b56a80999a8124e10f125ab079d0edbd94a315",
    "2315bb247a408d2009c84ebe28365a92ee53e8b283d2cc5d6bb7c5126ff5cd8d",
    "97684c029da1e955674b78744ef14cdb3c350585ff3dc452bec81aa99b725936",
    "8ca613e19f6195c03b5532b3a86d19487068e988264bc6ce4e40c611e0978520",
    "0761223c1d5a070ac08a99f45fcb976d48eb6cab49dfaa795f88963ac8b091ed",
    "13faa13c24c87abc51f96f0053e9855e2212018a8de3ac6a4375e2c5fb929be3",
    "98a37cf1c80e24a9928554fe760af5176f924eed2b0a26df9e135dad8000503b",
    "1efd14e7e885ead4146d4cc55ddaa76e83f88d6453c70b68b8b7a4d4a5a050ce",
    "9a5c8c8320535aa9255a7dbe343ab7bf23e4b3cee45c792908b53ba5aa826b9a",
    "e03a9e30f930571f202c5b7944318fb895d909275788ef7908fc2f6a84f6b955",
    "016d216e5ca95b0ff9bd8c7f6dc5e680e226aec019905dff89b8ae0491002497",
    "9bce8bfde16c7b38a98926bb0bad7242775d71065b69715acc3230349bd44660",
    "eb69e16f78aa7eaf689d1f6cc44662d9b7032cfde8e976d208e1f049701ec0b4",
    "d34ac8b0465eb162f726d3a7cc36f317f6becd883422e04472c2110466fea709",
    "96bff32c86c49f104efc19560504f5097445cbd20f83b3b106e037e687510286",
    "4ef1cd4b1efb58f3e5f6a4ef2e85a49d87fe94e7870e43b2550e63f2a655cb9e",
    "c24ac033440ebb4ae6ab2ef614f48ec0a53b33aeaa7832e13f78ae0216f76cdc",
    "80e31e06244f59acb5007ad8fdd02c16834d3067df9fd5b42fd9cd3cc2236e1b",
    "b0ea9d498fa1c6acd2702562778efdc3f008c626dfae0df45d39c975ac5f76f6",
    "ccf99b533bf3ac097167e72b8c6cf067df5a96977f9087452962cf3dfa7d4de6",
    "72e334a54084381e86466566df0b01f366c9f8ab48494e4a9acf9bc90da92606",
    "bb3d0d933d53bfc077d84cb67a991a4112a4c96be8c1aac61e8a04e7f8370d40",
    "df2fc598532245738f4631c5ccf4fd62748b129a41e30be6909fd858fa7e3375",
    "29baa4ff15eb34c060d9d49457179f70a126e599d30ba6075b87e84e192309e4",
    "aea390666970ebe6b545997b036cdcc0efa2146e48f997be6074a100cd6d33de",
    "d37eb8c36e7a86e0cb414afabdd23d3865104dc7a233e0b0893e95cb2ac694f2",
    "ea9eca7866346a8dba99d1877d4c019c3305cd37056bc7884148dd927d996f38",
    "31a3f2632f2ae57761f171b4750a008de8fc423e2e54a6194877865f2d9e9a76",
    "ea180dec1ad5d1e52ffa2f1838a8551a59587b88e8831d71bef961cb7b0b5be8"
  ],
  "complete_candidate_relation_set_hash": "7d2b50ab9269c6f867925fa4f704ef7957e7a2685d68845638ac971d55a4aeca",
  "complete_candidate_universe_hash": "4ba44bae9b5dd5fdeda1cd988215d8a3f1e6d58d85e36e6c7710f917e79a1901",
  "execution_manifest_id": "9a76ac35974fe15fcac5031dff26576ed4fedd28bdbb4aece6302f8a7515b589",
  "historical_output_denylist_hash": "f2f48a3142bf192c08cfa2bffbb722e0131bfd4a1ba55623caf5af72748b94c7",
  "input_status": "FROZEN_PREPARATION_ONLY",
  "proposal_evidence_profile_hash": "e24746c96c5f741cc35df8d992d93936911dd1de2ce7f1a0f00035cda3b33deb",
  "proposal_input_bundle_id": "8dbda558d7029606afddfcdb4facdbf23d5ea7b01418390ec503ba3480dec656",
  "raw_identity_hash": "33af79bd98b6364bc6570b4e6031ff8b21f1fa537fbb09d0ab747813ce668cd6",
  "raw_key": "6000006::S04::A006",
  "raw_source_bundle_hash": "a80daf63d9573c3b6b923a9c4329b1039681720857beddd662a3ffbd5a097747",
  "schema": "PROPOSAL_INPUT_BUNDLE_CONTRACT_V1",
  "source_class_fact_type_registry_id": "8cef6206dfc3581c3e7b6358bde7a36e90f4ba99078176cc0e5aff4b238298a7"
}
