=== cphzyl1611/apt-experiment-artifacts/current86-r4/FA1B2de_Current86_BSO_A2_P0_P1_Execution_Contract_R5/00_lineage/r2_baseline/05_schemas/raw_execution_unit.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": false,
  "properties": {
    "adjudication_executed": {
      "const": false
    },
    "authority_scope_id": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    },
    "complete_candidate_relation_set_hash": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    },
    "complete_candidate_universe_hash": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    },
    "execution_manifest_id": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    },
    "initial_current_state": {
      "const": "NOT_STARTED_FOR_ADJUDICATION"
    },
    "p0_prepared": {
      "const": true
    },
    "raw_execution_unit_id": {
      "anyOf": [
        {
          "pattern": "^[0-9a-f]{64}$",
          "type": "string"
        },
        {
          "const": null
        }
      ]
    },
    "raw_identity_hash": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    },
    "raw_key": {
      "pattern": "^[0-9]+::S[0-9]{2}::A[0-9]{3}$",
      "type": "string"
    },
    "schema": {
      "minLength": 1,
      "type": "string"
    },
    "source_bundle_status": {
      "const": "FROZEN_REFERENCE_ONLY_NOT_RUNTIME_MATERIALIZED"
    }
  },
  "required": [
    "schema",
    "raw_key",
    "authority_scope_id",
    "execution_manifest_id",
    "raw_identity_hash",
    "complete_candidate_universe_hash",
    "complete_candidate_relation_set_hash",
    "source_bundle_status",
    "initial_current_state",
    "p0_prepared",
    "adjudication_executed",
    "raw_execution_unit_id"
  ],
  "schema_id": "0abc065ad48ca0292e0874ec79f66c4f892d482dab684243027b27064c2d85a2",
  "title": "Current86 raw execution unit",
  "type": "object"
}

=== cphzyl1611/apt-experiment-artifacts/current86-r4/FA1B2de_Current86_BSO_A2_P0_P1_Execution_Contract_R5/05_schemas/execution_units/6000007__S08__A006.json
{
  "adjudication_executed": false,
  "authority_scope_id": "34551e904bafa71fb2fb6db33162e94ad41a08eca6c747d429c83760e09c1306",
  "complete_candidate_relation_set_hash": "d4d632d4fb5dd0761f6fd76111d0dccaca0b0c2a541980b2288dca366e8a555e",
  "complete_candidate_universe_hash": "c0e2c8e58d6824230e3f24ac430013369963418a8b4ab99e8fc47b3dd2ed48f5",
  "execution_manifest_id": "9a76ac35974fe15fcac5031dff26576ed4fedd28bdbb4aece6302f8a7515b589",
  "initial_current_state": "NOT_STARTED_FOR_ADJUDICATION",
  "p0_prepared": true,
  "raw_execution_unit_id": "02c9e97745e3f8b3389640ae5fc5d8e5afb6cb9ce07e55917c50d89e6de988c9",
  "raw_identity_hash": "b49051b124b11bd7cba543091f4524bf2047ca269a872b7baab3ee4bdd79de67",
  "raw_key": "6000007::S08::A006",
  "schema": "RAW_EXECUTION_UNIT_CONTRACT_V1",
  "source_bundle_status": "FROZEN_REFERENCE_ONLY_NOT_RUNTIME_MATERIALIZED"
}

=== cphzyl1611/apt-experiment-artifacts/current86-r4/FA1B2de_Current86_BSO_A2_P0_P1_Execution_Contract_R5/00_lineage/r3_baseline/05_schemas/execution_units/6000007__S04__A001.json
{
  "adjudication_executed": false,
  "authority_scope_id": "34551e904bafa71fb2fb6db33162e94ad41a08eca6c747d429c83760e09c1306",
  "complete_candidate_relation_set_hash": "c4909f2841cd4f588c819914d61ffba0446b0c803d573e96d15e975e3cbbf4da",
  "complete_candidate_universe_hash": "3a29a862b2198d8057d7c06ef7caf8c97a8cbf76b5e4f864b5ddbcf60425efec",
  "execution_manifest_id": "9a76ac35974fe15fcac5031dff26576ed4fedd28bdbb4aece6302f8a7515b589",
  "initial_current_state": "NOT_STARTED_FOR_ADJUDICATION",
  "p0_prepared": true,
  "raw_execution_unit_id": "15d841a58e5918d81753c262b5df53d6df7cbb3a1fab70fba1c0a0a84dd608ce",
  "raw_identity_hash": "55b9dc0da5ecf2866f5b610703b92587b89e999db32739503df7038b2ed13fe7",
  "raw_key": "6000007::S04::A001",
  "schema": "RAW_EXECUTION_UNIT_CONTRACT_V1",
  "source_bundle_status": "FROZEN_REFERENCE_ONLY_NOT_RUNTIME_MATERIALIZED"
}

=== cphzyl1611/apt-experiment-artifacts/current86-r4/FA1B2de_Current86_BSO_A2_P0_P1_Execution_Contract_R5/00_lineage/r4_baseline/00_lineage/r3_baseline/00_lineage/r2_baseline/05_schemas/execution_units/6000007__S03__A011.json
{
  "adjudication_executed": false,
  "authority_scope_id": "34551e904bafa71fb2fb6db33162e94ad41a08eca6c747d429c83760e09c1306",
  "complete_candidate_relation_set_hash": "e86191a32c2132e8556f09a56286a28231096ceccdfae4470652e73900ca181c",
  "complete_candidate_universe_hash": "792966724ff80b9aeeadc866b5b93e3875cde39f7e9a2ce5e92481ab80f6f564",
  "execution_manifest_id": "9a76ac35974fe15fcac5031dff26576ed4fedd28bdbb4aece6302f8a7515b589",
  "initial_current_state": "NOT_STARTED_FOR_ADJUDICATION",
  "p0_prepared": true,
  "raw_execution_unit_id": "5a7913aa664dd091ee82f922a368a112e351dff733fcaf3f7874c7938e0721c1",
  "raw_identity_hash": "a8f8e246258f34baab582cbcbc08682f83a5c76571a4565132013c95a72e1b04",
  "raw_key": "6000007::S03::A011",
  "schema": "RAW_EXECUTION_UNIT_CONTRACT_V1",
  "source_bundle_status": "FROZEN_REFERENCE_ONLY_NOT_RUNTIME_MATERIALIZED"
}

=== cphzyl1611/apt-experiment-artifacts/current86-r4/FA1B2de_Current86_BSO_A2_P0_P1_Execution_Contract_R4/05_schemas/execution_units/6000002__S08__A004.json
{
  "adjudication_executed": false,
  "authority_scope_id": "34551e904bafa71fb2fb6db33162e94ad41a08eca6c747d429c83760e09c1306",
  "complete_candidate_relation_set_hash": "d5eb422b8c1f2beb6e22f666bf8552a518471daa1eab330b043a920d89aea568",
  "complete_candidate_universe_hash": "5a13389453a688f5be12440fd5bf5998201bb7458f624a72d4563f11ff32d48a",
  "execution_manifest_id": "9a76ac35974fe15fcac5031dff26576ed4fedd28bdbb4aece6302f8a7515b589",
  "initial_current_state": "NOT_STARTED_FOR_ADJUDICATION",
  "p0_prepared": true,
  "raw_execution_unit_id": "0400a87ca39120a2e6028887df45cc588aba9c0bc32fd1a77d750d2652f33c5f",
  "raw_identity_hash": "a13978d61734d7311d23f22eb225209ad9b2a23d2576f57d14aed26c18b1d7f1",
  "raw_key": "6000002::S08::A004",
  "schema": "RAW_EXECUTION_UNIT_CONTRACT_V1",
  "source_bundle_status": "FROZEN_REFERENCE_ONLY_NOT_RUNTIME_MATERIALIZED"
}

=== cphzyl1611/apt-experiment-artifacts/current86-r4/FA1B2de_Current86_BSO_A2_P0_P1_Execution_Contract_R4/00_lineage/r3_baseline/00_lineage/r2_baseline/05_schemas/execution_units/6000007__S07__A002.json
{
  "adjudication_executed": false,
  "authority_scope_id": "34551e904bafa71fb2fb6db33162e94ad41a08eca6c747d429c83760e09c1306",
  "complete_candidate_relation_set_hash": "c4e0a1d74caf86311bde09b534506f946ad736374fa594dce5324e62845500dc",
  "complete_candidate_universe_hash": "988e7992077540c915807c5eebbccd83dea75c80715f9a40337d2491c6f12135",
  "execution_manifest_id": "9a76ac35974fe15fcac5031dff26576ed4fedd28bdbb4aece6302f8a7515b589",
  "initial_current_state": "NOT_STARTED_FOR_ADJUDICATION",
  "p0_prepared": true,
  "raw_execution_unit_id": "c260f4d6d886674e077de3662708584bc2effefdd628f754ddc5a4e2c5a3111f",
  "raw_identity_hash": "c1c9bb547d1dc4b0fd6e0c10302b94969134db38f4dc005238b67dee35d9ed61",
  "raw_key": "6000007::S07::A002",
  "schema": "RAW_EXECUTION_UNIT_CONTRACT_V1",
  "source_bundle_status": "FROZEN_REFERENCE_ONLY_NOT_RUNTIME_MATERIALIZED"
}

=== cphzyl1611/apt-experiment-artifacts/current86-r4/FA1B2de_Current86_BSO_A2_P0_P1_Execution_Contract_R5/00_lineage/r4_baseline/00_lineage/r3_baseline/00_lineage/r2_baseline/05_schemas/execution_units/6000006__S12__A001.json
{
  "adjudication_executed": false,
  "authority_scope_id": "34551e904bafa71fb2fb6db33162e94ad41a08eca6c747d429c83760e09c1306",
  "complete_candidate_relation_set_hash": "a05a0c49fa6cf9ca3341bcc9271afccf6160b86873162c254d13d8dad2037558",
  "complete_candidate_universe_hash": "99862cd3dd30af604f0d9936c786da6e0ca9ecc1eee82d1364997ae85075612a",
  "execution_manifest_id": "9a76ac35974fe15fcac5031dff26576ed4fedd28bdbb4aece6302f8a7515b589",
  "initial_current_state": "NOT_STARTED_FOR_ADJUDICATION",
  "p0_prepared": true,
  "raw_execution_unit_id": "d6344a76ae17045a055c673f6db079ef5a04d4ccaa5bec04aceea8dec3ec8168",
  "raw_identity_hash": "557c4bdd5b81639c3be969ceb5301ff6a1b9b87a02c18366dea006f3b0957839",
  "raw_key": "6000006::S12::A001",
  "schema": "RAW_EXECUTION_UNIT_CONTRACT_V1",
  "source_bundle_status": "FROZEN_REFERENCE_ONLY_NOT_RUNTIME_MATERIALIZED"
}

=== cphzyl1611/apt-experiment-artifacts/current86-r4/FA1B2de_Current86_BSO_A2_P0_P1_Execution_Contract_R5/00_lineage/r3_baseline/05_schemas/execution_units/6000006__S02__A002.json
{
  "adjudication_executed": false,
  "authority_scope_id": "34551e904bafa71fb2fb6db33162e94ad41a08eca6c747d429c83760e09c1306",
  "complete_candidate_relation_set_hash": "ca49d4ae7ed294be03ecfa8f18222e26e3f21ad11800d426d78a621e3be7f361",
  "complete_candidate_universe_hash": "89aeacc2b21cef989deb9454ef0fc4edb0aa0ddfe5c81d7fee99d7dd1cc52692",
  "execution_manifest_id": "9a76ac35974fe15fcac5031dff26576ed4fedd28bdbb4aece6302f8a7515b589",
  "initial_current_state": "NOT_STARTED_FOR_ADJUDICATION",
  "p0_prepared": true,
  "raw_execution_unit_id": "55840cac3ffe9d7aa91ca7e08a763f944515c730baa1928234eb5d9d6986788b",
  "raw_identity_hash": "8e7bcdf4181250c188b3dd700f727b27844d46085acb3438ed1698411a6e7e3e",
  "raw_key": "6000006::S02::A002",
  "schema": "RAW_EXECUTION_UNIT_CONTRACT_V1",
  "source_bundle_status": "FROZEN_REFERENCE_ONLY_NOT_RUNTIME_MATERIALIZED"
}

=== cphzyl1611/apt-experiment-artifacts/current86-r4/FA1B2de_Current86_BSO_A2_P0_P1_Execution_Contract_R5/00_lineage/r3_baseline/05_schemas/execution_units/6000007__S03__A006.json
{
  "adjudication_executed": false,
  "authority_scope_id": "34551e904bafa71fb2fb6db33162e94ad41a08eca6c747d429c83760e09c1306",
  "complete_candidate_relation_set_hash": "84c5689f440b42b2a0241c141918f65f06686759d543ad00a8b0a5f8abe4da80",
  "complete_candidate_universe_hash": "fb2e946d549139b2c16bfa19e9b3c32c4da280172a0554dbc537e0f38c00c895",
  "execution_manifest_id": "9a76ac35974fe15fcac5031dff26576ed4fedd28bdbb4aece6302f8a7515b589",
  "initial_current_state": "NOT_STARTED_FOR_ADJUDICATION",
  "p0_prepared": true,
  "raw_execution_unit_id": "b3c21827cb1b403b642d23b5829a7d94d95d6af64a905c34188d486c728691fe",
  "raw_identity_hash": "6dff85ecc7c02bec5eb7f90c300f47a949cb22c6449ae73a3d5cfe49c09aed87",
  "raw_key": "6000007::S03::A006",
  "schema": "RAW_EXECUTION_UNIT_CONTRACT_V1",
  "source_bundle_status": "FROZEN_REFERENCE_ONLY_NOT_RUNTIME_MATERIALIZED"
}
