=== cphzyl1611/apt-experiment-artifacts/current86-r4/FA1B2de_Current86_BSO_A2_P0_P1_Execution_Contract_R5/00_lineage/r2_baseline/05_schemas/raw_execution_unit.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": false,
  "properties": {
    "adjudication_executed": {
      "const": false
    },
    "authority_scope_id": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    },
    "complete_candidate_relation_set_hash": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    },
    "complete_candidate_universe_hash": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    },
    "execution_manifest_id": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    },
    "initial_current_state": {
      "const": "NOT_STARTED_FOR_ADJUDICATION"
    },
    "p0_prepared": {
      "const": true
    },
    "raw_execution_unit_id": {
      "anyOf": [
        {
          "pattern": "^[0-9a-f]{64}$",
          "type": "string"
        },
        {
          "const": null
        }
      ]
    },
    "raw_identity_hash": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    },
    "raw_key": {
      "pattern": "^[0-9]+::S[0-9]{2}::A[0-9]{3}$",
      "type": "string"
    },
    "schema": {
      "minLength": 1,
      "type": "string"
    },
    "source_bundle_status": {
      "const": "FROZEN_REFERENCE_ONLY_NOT_RUNTIME_MATERIALIZED"
    }
  },
  "required": [
    "schema",
    "raw_key",
    "authority_scope_id",
    "execution_manifest_id",
    "raw_identity_hash",
    "complete_candidate_universe_hash",
    "complete_candidate_relation_set_hash",
    "source_bundle_status",
    "initial_current_state",
    "p0_prepared",
    "adjudication_executed",
    "raw_execution_unit_id"
  ],
  "schema_id": "0abc065ad48ca0292e0874ec79f66c4f892d482dab684243027b27064c2d85a2",
  "title": "Current86 raw execution unit",
  "type": "object"
}

=== cphzyl1611/apt-experiment-artifacts/current86-r4/FA1B2de_Current86_BSO_A2_P0_P1_Execution_Contract_R4/00_lineage/r3_baseline/00_lineage/r2_baseline/05_schemas/execution_units/6000007__S09__A004.json
{
  "adjudication_executed": false,
  "authority_scope_id": "34551e904bafa71fb2fb6db33162e94ad41a08eca6c747d429c83760e09c1306",
  "complete_candidate_relation_set_hash": "1d578834df280b732638356207c97f101a46fb22fbbe3ce9d95b18552f502140",
  "complete_candidate_universe_hash": "53f50aa43b370d404157e48519bbeef0a308d0a085fe89ecfd81b5f219cbba64",
  "execution_manifest_id": "9a76ac35974fe15fcac5031dff26576ed4fedd28bdbb4aece6302f8a7515b589",
  "initial_current_state": "NOT_STARTED_FOR_ADJUDICATION",
  "p0_prepared": true,
  "raw_execution_unit_id": "f54ae4b81547cc1d7317d0a50cadc1383bf66d7dd06c67b47fbbf37f3e13c3bc",
  "raw_identity_hash": "7c5079be4a965da9a6f61436e1c2c945acd28ff6374307349d81256511dd1103",
  "raw_key": "6000007::S09::A004",
  "schema": "RAW_EXECUTION_UNIT_CONTRACT_V1",
  "source_bundle_status": "FROZEN_REFERENCE_ONLY_NOT_RUNTIME_MATERIALIZED"
}

=== cphzyl1611/apt-experiment-artifacts/current86-r4/FA1B2de_Current86_BSO_A2_P0_P1_Execution_Contract_R5/00_lineage/r4_baseline/00_lineage/r2_baseline/05_schemas/execution_units/6000006__S08__A006.json
{
  "adjudication_executed": false,
  "authority_scope_id": "34551e904bafa71fb2fb6db33162e94ad41a08eca6c747d429c83760e09c1306",
  "complete_candidate_relation_set_hash": "81d975c4bd9dd6005bb7b657ad31acb1223d95a9ef2f8f4f0b7cac302db8d061",
  "complete_candidate_universe_hash": "02f64e7137a5d2a1049c8382f2858487f29235c991b559dee2a8f22ccf8b60d7",
  "execution_manifest_id": "9a76ac35974fe15fcac5031dff26576ed4fedd28bdbb4aece6302f8a7515b589",
  "initial_current_state": "NOT_STARTED_FOR_ADJUDICATION",
  "p0_prepared": true,
  "raw_execution_unit_id": "b66adb0766bcc22d9d0f5bb5c7d10cea650f2152095c42c4824f1f65d76e9aa3",
  "raw_identity_hash": "4094494ebf4be20b1ccbfa48efb27ff5f90e555b78f2c1becbb0ebf1804f93c2",
  "raw_key": "6000006::S08::A006",
  "schema": "RAW_EXECUTION_UNIT_CONTRACT_V1",
  "source_bundle_status": "FROZEN_REFERENCE_ONLY_NOT_RUNTIME_MATERIALIZED"
}

=== cphzyl1611/apt-experiment-artifacts/current86-r4/FA1B2de_Current86_BSO_A2_P0_P1_Execution_Contract_R5/00_lineage/r4_baseline/00_lineage/r3_baseline/00_lineage/r2_baseline/05_schemas/execution_units/6000007__S04__A003.json
{
  "adjudication_executed": false,
  "authority_scope_id": "34551e904bafa71fb2fb6db33162e94ad41a08eca6c747d429c83760e09c1306",
  "complete_candidate_relation_set_hash": "fd14a54fcf1c867fc2dbea55d1a6210c8170dd128b10f8558875bf142d87dc03",
  "complete_candidate_universe_hash": "8cfd2d988f472790ea29d7ffc63864d4fff58e03a4bb933b3aef640d39b65c6b",
  "execution_manifest_id": "9a76ac35974fe15fcac5031dff26576ed4fedd28bdbb4aece6302f8a7515b589",
  "initial_current_state": "NOT_STARTED_FOR_ADJUDICATION",
  "p0_prepared": true,
  "raw_execution_unit_id": "ad025ee90cb85a1c8d221d2dae001cb08521733563f69e2092d016a490ed5889",
  "raw_identity_hash": "87e75ac28aaa4b59e3c1014ba72ecbc96e97356818b85ea7fb3c4c55bc6f9a2f",
  "raw_key": "6000007::S04::A003",
  "schema": "RAW_EXECUTION_UNIT_CONTRACT_V1",
  "source_bundle_status": "FROZEN_REFERENCE_ONLY_NOT_RUNTIME_MATERIALIZED"
}

=== cphzyl1611/apt-experiment-artifacts/current86-r4/FA1B2de_Current86_BSO_A2_P0_P1_Execution_Contract_R5/00_lineage/r4_baseline/00_lineage/r2_baseline/05_schemas/execution_units/6000008__S06__A002.json
{
  "adjudication_executed": false,
  "authority_scope_id": "34551e904bafa71fb2fb6db33162e94ad41a08eca6c747d429c83760e09c1306",
  "complete_candidate_relation_set_hash": "23cbf6c0b5b5c7c57b1ec1dc37e602143d664c80966a5f4d669201454456165f",
  "complete_candidate_universe_hash": "7ef5e29b3d7257d65ba441feba13fa0f7b7803a1d408eea434ad690d5ef44bb7",
  "execution_manifest_id": "9a76ac35974fe15fcac5031dff26576ed4fedd28bdbb4aece6302f8a7515b589",
  "initial_current_state": "NOT_STARTED_FOR_ADJUDICATION",
  "p0_prepared": true,
  "raw_execution_unit_id": "efec619b10ed2a305fdd514cc5ad6756cc1ccc4e18dd9819a0c178cac28d8e82",
  "raw_identity_hash": "614ca68414883396e93452c531d2bcfe76c7cc9af7764f2afc4ba02933ae60e9",
  "raw_key": "6000008::S06::A002",
  "schema": "RAW_EXECUTION_UNIT_CONTRACT_V1",
  "source_bundle_status": "FROZEN_REFERENCE_ONLY_NOT_RUNTIME_MATERIALIZED"
}

=== cphzyl1611/apt-experiment-artifacts/current86-r4/FA1B2de_Current86_BSO_A2_P0_P1_Execution_Contract_R4/05_schemas/execution_units/6000006__S04__A001.json
{
  "adjudication_executed": false,
  "authority_scope_id": "34551e904bafa71fb2fb6db33162e94ad41a08eca6c747d429c83760e09c1306",
  "complete_candidate_relation_set_hash": "0e5b562f6abedf60ca33a4b090f931468795f4ad9b9181d1719975556a77e325",
  "complete_candidate_universe_hash": "e9e751b0b3cbbcea36bb067b9493f7f527d4f7c729e1ab85c209930e962a8c0a",
  "execution_manifest_id": "9a76ac35974fe15fcac5031dff26576ed4fedd28bdbb4aece6302f8a7515b589",
  "initial_current_state": "NOT_STARTED_FOR_ADJUDICATION",
  "p0_prepared": true,
  "raw_execution_unit_id": "bdb527889527c147326131f68eec9904fb845006b494924cfec4fe53fa2992bd",
  "raw_identity_hash": "e692cb966a6e98c682fa302b3af179b5ba5834ad8f777d2c80a80f86cc45c140",
  "raw_key": "6000006::S04::A001",
  "schema": "RAW_EXECUTION_UNIT_CONTRACT_V1",
  "source_bundle_status": "FROZEN_REFERENCE_ONLY_NOT_RUNTIME_MATERIALIZED"
}

=== cphzyl1611/apt-experiment-artifacts/current86-r4/FA1B2de_Current86_BSO_A2_P0_P1_Execution_Contract_R4/05_schemas/execution_units/6000006__S07__A007.json
{
  "adjudication_executed": false,
  "authority_scope_id": "34551e904bafa71fb2fb6db33162e94ad41a08eca6c747d429c83760e09c1306",
  "complete_candidate_relation_set_hash": "a5f39675f0dce100b7f5839c9641137ed386303554f4ca35c0fb33fa1ec43ab8",
  "complete_candidate_universe_hash": "1b2688e5aaf01e699b4eb2189e5eb87b39952872665521ab0b0039b42a90c28e",
  "execution_manifest_id": "9a76ac35974fe15fcac5031dff26576ed4fedd28bdbb4aece6302f8a7515b589",
  "initial_current_state": "NOT_STARTED_FOR_ADJUDICATION",
  "p0_prepared": true,
  "raw_execution_unit_id": "b4fb54375f1d8c279026e8ee4a1d6f4f0828199cd3ce96f73b1ccf0041bd88a9",
  "raw_identity_hash": "4c3c0eecae1174376d5a23a65c2859938dc410db4a71be8e13154f593788e4a2",
  "raw_key": "6000006::S07::A007",
  "schema": "RAW_EXECUTION_UNIT_CONTRACT_V1",
  "source_bundle_status": "FROZEN_REFERENCE_ONLY_NOT_RUNTIME_MATERIALIZED"
}

=== cphzyl1611/apt-experiment-artifacts/current86-r4/FA1B2de_Current86_BSO_A2_P0_P1_Execution_Contract_R5/00_lineage/r4_baseline/05_schemas/execution_units/6000008__S05__A001.json
{
  "adjudication_executed": false,
  "authority_scope_id": "34551e904bafa71fb2fb6db33162e94ad41a08eca6c747d429c83760e09c1306",
  "complete_candidate_relation_set_hash": "754d801eb85cee820d4de9ff331ac900f3f9c875512289d6408d754c890886f4",
  "complete_candidate_universe_hash": "e79f72fcecbfe1496f438487a5206f1ca9a84269a1e4d01fb05b323718cd55a5",
  "execution_manifest_id": "9a76ac35974fe15fcac5031dff26576ed4fedd28bdbb4aece6302f8a7515b589",
  "initial_current_state": "NOT_STARTED_FOR_ADJUDICATION",
  "p0_prepared": true,
  "raw_execution_unit_id": "2f4647692db71cde2534b924a53beb8e26ad538ca0a600e7b280b45c49aa134f",
  "raw_identity_hash": "193ee18bf4149196221f0ede9d00a6a3d964f0a014a17cb9728a2c1b4c6b8678",
  "raw_key": "6000008::S05::A001",
  "schema": "RAW_EXECUTION_UNIT_CONTRACT_V1",
  "source_bundle_status": "FROZEN_REFERENCE_ONLY_NOT_RUNTIME_MATERIALIZED"
}

=== cphzyl1611/apt-experiment-artifacts/current86-r4/FA1B2de_Current86_BSO_A2_P0_P1_Execution_Contract_R5/00_lineage/r2_baseline/05_schemas/execution_units/6000003__S06__A002.json
{
  "adjudication_executed": false,
  "authority_scope_id": "34551e904bafa71fb2fb6db33162e94ad41a08eca6c747d429c83760e09c1306",
  "complete_candidate_relation_set_hash": "0e13c04dc6640cafb7a835db017c330cb88e453d3f981efc08b865fea7dffdc3",
  "complete_candidate_universe_hash": "6b045eec1c5b62e96c70867cd00184cb431d1b38d5a39024fc9b4330cbb3f672",
  "execution_manifest_id": "9a76ac35974fe15fcac5031dff26576ed4fedd28bdbb4aece6302f8a7515b589",
  "initial_current_state": "NOT_STARTED_FOR_ADJUDICATION",
  "p0_prepared": true,
  "raw_execution_unit_id": "265b476b5541e7d7bd74433c1ac434778bf0477116dacf9fe96a23f7c5944998",
  "raw_identity_hash": "9b123a65d77304666775bc5b7f5de8092f73a81506a2be212002f7cd09f109b2",
  "raw_key": "6000003::S06::A002",
  "schema": "RAW_EXECUTION_UNIT_CONTRACT_V1",
  "source_bundle_status": "FROZEN_REFERENCE_ONLY_NOT_RUNTIME_MATERIALIZED"
}
